### ISSUE TITLE
[🐞]: Weird crash issue on startup

### ISSUE THREAD

**Issue by sirben99** [MehVahdJukaar/WoodGood#327] opened 2023-11-05 17:21 UTC
### Before Continuing:

- [x] Always check you are using the latest version of the mods and its dependencies
- [ ] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [ ] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.16-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.56-fabric

### Issue with mods

better-nether-9.0.9 (?)
furnish-25-fabric (?)

### Issue Detail

Hey!

I have an strange issue where EveryCompat is crashing on startup. It only happens with the 2.6.16 version of Every Compat (2.6.15 works without any issues) and with any version of the mod Furnish (24-25). I have over 500 mods, so binary searching what exactly is causing this is hard, but i submitted this in case it could be solved with the logs. If not, i can try to binary the pack to see whats causing it.

I have tested the mods together in a separate instance, and they work fine.

I have tested: 
Disable Reed in the config for BetterNether
Disable Furnish Chair in the config

No luck, still the same crash.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/13260351/latest.log)
[crash-2023-11-05_19.15.11-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13260353/crash-2023-11-05_19.15.11-client.txt)

**Comment by Xelbayria** [comment] 2023-11-05 18:58
Weird. It looks like the issue is with Better Nether mod.  MehVadJukaar and I already are investigating this

EDIT:
@sirben99 
Can you put the file: `everycomp-common.toml` here, there is something I want to check. I've seen a similar issue like this before.  the file                                    👆  will tell me which mod is the issue.

**Comment by sirben99** [comment] 2023-11-05 19:11
Ofc! I havent edited any values, but here it is: 
[everycomp-common.json](https://github.com/MehVahdJukaar/WoodGood/files/13260566/everycomp-common.json)

It is in .json format, is that a problem since you asked for .toml?

**Comment by Xelbayria** [comment] 2023-11-05 19:17
> 
> It is in .json format, is that a problem since you asked for .toml?

No problem. Alright, I found a similar wood type from 2 mods: **Better Nether**, **biomemakeover**, **natures_spirit**, **regions_unexplored**

can you disable all of them except **Better Nether** and run to see if minecraft still crash with just one mod.  

if not, then enable 1 of these disabled 3 mods and try again until you get a crash.

**Comment by Xelbayria** [comment] 2023-11-05 19:20
> It is in .json format, is that a problem since you asked for .toml?

no problem. I'll investigate this to find out what's the cause by reproducing the crash if i can 

EDIT: 
ok i wasn't able to reproduce the crashing. is your modpack an official one or just self-made. 
If it's an official one, then try do a clean installation of the modpack AND backup your singleplayer world if you played. 

self-made, if you don't mind, try find the mod that caused the problem. 

I've run and tested with latest version: EveryComp, Moonlight, Furnish & BetterNether. no crash. so Something must be causing that crash.

**Comment by sirben99** [comment] 2023-11-05 19:36
I am currently trying the method you suggested. The modpack is self made kitchen sink modpack. If the above method doesent work, ill try to binary the pack tomorrow (Its getting late for today)

**Comment by Xelbayria** [comment] 2023-11-05 19:38
Alright, Try focus on mods that has chair and if they are ruled out. Furnish has one. There should be other mods that also offer the same furniture, CHAIR 
Good night! 

EDIT: 
btw, the chair from what I see in TOML file.   two mods have chairs are: **Furnish** & **Another Furniture**

**Comment by sirben99** [comment] 2023-11-05 19:46
Unfortunately removing the mods mentioned here and also disabling them doesent seem to do anything. I also noticed, when using the 2.6.15 version of EveryCompat (The one that works), all the chairs dont have textures. Ill try to get to the bottom of this tomorrow

**Comment by Xelbayria** [comment] 2023-11-05 19:58
Found the cause: 
i just run with: 
- EveryComp 
- Moonlight 
- Furnish 👈 
- BetterNether
- Another Furniture 👈 

above caused the crash. I also checked the log, same log as your.

**Comment by sirben99** [comment] 2023-11-05 20:02
Nice! What kinda confuses me tho is that i have removed Another Furniture from my modpack, and the crash still happens. I assume there are other mods that can also cause the error

**Comment by Xelbayria** [comment] 2023-11-05 20:07
> Nice! What kinda confuses me tho is that i have removed Another Furniture from my modpack, and the crash still happens. I assume there are other mods that can also cause the error

like i said 
> Alright, Try focus on mods that has chair and if they are ruled out

Mods that offer furniture. like CHAIR. it looks like your TOML is not full because you removed a few mods so **Another Furniture** wasn't in there. 

Idk what caused this problem. I've seen one issue with similar furniture causing the crash. The author & I wasn't able to determine the cause. I think it's Moonlight. MehVuhJukaar said he has a good idea of what's going on. 

once you know which mods caused the crash, you'll have to make a choice for which mods to be excluded so you can play for now. **so get some rest & talk later!**

**Comment by sirben99** [comment] 2023-11-05 20:16
Ill look into what mods could cause the crash and report to you! I will now catch your advice and go get some rest haha. Good night!

**Comment by Xelbayria** [comment] 2024-02-22 23:21
Ok. i ran test with the latest version: 
- **EveryCompat** v2.6.33
- **Moonlight Lib** v2.10.2

with the mods mentioned above that caused the crash.  it looks like the crash have been solved. this is also mentioned in another issue above which have been solved with **BetterEnd**.  

closing this.

**Closed as completed by Xelbayria** 2024-02-22 23:21 UTC
Labels: bug, 1.20.1-FABRIC

**Comment by sirben99** [comment] 2024-02-23 08:28
Hey!

I just wanted to write here that im super sorry that i havent reported back to this issue when i promised to. I was going to start solving it the next day i sayd i would, but then life started to happen, got a job etc and i dint find time to solve it anymore and eventually forgot about it. Im super glad all works now and im terribly sorry for wasting your time.

**Comment by Xelbayria** [comment] 2024-02-23 09:46
No worries. We all have our lives to tend to. Even you did not report this issue. someone else would have and it would still get solved in the end. 

Take care.
