### ISSUE TITLE
[🐞]: Woodster not registering bookshelf recipies

### ISSUE THREAD

**Issue by dadobug1111** [MehVahdJukaar/WoodGood#361] opened 2023-12-11 22:26 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.18

### Moonlight Lib Version

moonlight-1.20-2.8.67

### Issue with mods

woodster-1.4.5

### Issue Detail

any new bookshelves generated do not have crafting recipes

### OPTIONAL: To Produce

1 - load game with woodster, jei, and any mod that adds another wood type.
2 - Check recipes for new bookshelves.
3 - Observe no recipes for generated shelves, but recipes for default shelves are present.

**Comment by Xelbayria** [comment] 2023-12-12 10:36
I looked into this and found the cause. The fixes will be in the next version.

**Closed as completed** 2024-02-14 01:31 UTC
Labels: bug, status: done, 1.20.1-FORGE
