### ISSUE TITLE
[🗃]: Quark compat requires an overhaul for 1.20.1

### ISSUE THREAD

**Issue by bubbyboytoo** [MehVahdJukaar/WoodGood#376] opened 2023-12-24 18:10 UTC
### Version

Beta 4.0-421

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/quark

### Details

Not 100% sure this is the right tag, sorry, but Quark's beta release for 1.20 has completely refactored how it works internally, so all mods including this one will have to update their compatibility for it. Right now I can confirm that the game crashes on startup with both Quark and EveryCompat installed.

https://forum.violetmoon.org/d/145-suppporter-beta-release-quark-40-421-for-minecraft-1201
> Regarding mod compatibility with existing mods on 1.20.1: Any mods that provide code-level Quark compatibility and have yet to update to Quark's new namespace will crash on loading. This is because we have moved every file around in the transition to the new loading system. If you have any mods that need updating, please kindly ask the authors in question to checkout the Quark zeta120 branch for details.

**Comment by MehVahdJukaar** [comment] 2023-12-24 18:14
Maybe you should check the recent changelogs. Also I work on quark too so Im well aware

**Comment by Xelbayria** [comment] 2023-12-24 18:14
Alright. I'll take a look at what has changed. 

edit:
don't worry about the tag. that's fine

**Comment by bubbyboytoo** [comment] 2023-12-24 18:39
> Maybe you should check the recent changelogs. Also I work on quark too so Im well aware

Oh, that's convenient. I'm still getting a crash when I drop it into my relatively large modpack that doesn't occur without EC installed (I did update to the latest version from today), I'm sure it'll shake out as other mods update but I'll drop the log here in case there is anything you guys can do about it.
[crash-2023-12-24_17.50.05-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13762588/crash-2023-12-24_17.50.05-client.txt)

**Comment by Rick-300** [comment] 2024-02-10 14:22
[MinecraftCrash1.zip](https://github.com/MehVahdJukaar/WoodGood/files/14229542/MinecraftCrash1.zip)
Can confirm that this issue is present.

**Comment by Xelbayria** [comment] 2024-02-10 19:00
> [MinecraftCrash1.zip](https://github.com/MehVahdJukaar/WoodGood/files/14229542/MinecraftCrash1.zip) Can confirm that this issue is present.

you need to update **Macaw's Trapdoor**, it's outdated. I've seen a similar crash report like this before. 

EDIT: 
`mcw-trapdoors-1.1.1-mc1.20.1forge.jar`, the new version is **v.1.1.2**.. **Every Compat** no longer support versions older than **v1.1.2** because a new type of trapdoor is added.

**Comment by Xelbayria** [comment] 2024-02-10 19:12
> > Maybe you should check the recent changelogs. Also I work on quark too so Im well aware
> 
> Oh, that's convenient. I'm still getting a crash when I drop it into my relatively large modpack that doesn't occur without EC installed (I did update to the latest version from today), I'm sure it'll shake out as other mods update but I'll drop the log here in case there is anything you guys can do about it. [crash-2023-12-24_17.50.05-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13762588/crash-2023-12-24_17.50.05-client.txt)
<strike>
Try uninstalling **Quark** & **Zeta**, and delete the configuration file for **Quark**. Then do a clean install of both mods and try again to see if the issue persists. 

**MehVahdJukaar** said the bug was fixed by him & he's part of **Quark**'s team 

EDIT: 
forgot to mention this: The issue is not on **Every Compat**'s side, it's on **Quark**'s side. which is why the report makes no sense to me. 
</strike>

ignore above. I made a mistake. **Quark** is outdated. **Zeta** expected to be used by **v236** which is the latest version for **Quark**

**Closed as completed** 2024-02-21 07:03 UTC
Labels: enhancement, Module, 1.20.1-FORGE
