### ISSUE TITLE
[🐞]: crash while server loading.

### ISSUE THREAD

**Issue by CloverCorp** [MehVahdJukaar/WoodGood#555] opened 2024-07-04 09:07 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-1.6.12

### Moonlight Lib Version

selene-1.18.2-1.17.14

### Issue with mods

The crash only happens when combined with woodworks (https://www.curseforge.com/minecraft/mc-mods/woodworks) 

### Issue Detail

Causes a crash on the serverside only making the server unable to start, singleplayer is completely fine.

**Comment by Xelbayria** [comment] 2024-07-04 17:49
I need the crash-report (you can drag the file here)

**Comment by CloverCorp** [comment] 2024-07-04 22:00
[crash-2024-07-04_16.57.14-fml.txt](https://github.com/user-attachments/files/16103091/crash-2024-07-04_16.57.14-fml.txt)
i believe this is it.

**Comment by Xelbayria** [comment] 2024-07-04 22:27
Yup, that's the one. And I see what's the problem. The server is saying that the required class is not found and cause a crash. I need to run a test on my side to see If i can reproduce it.

**Comment by Xelbayria** [comment] 2024-07-04 23:28
Found the cause and fixed it. Will be in **v1.6.13**

**Closed as completed by Xelbayria** 2024-07-04 23:28 UTC
Labels: bug, status: done, 1.18.2
