### ISSUE TITLE
[🐞]: Hedges using incorrect Fruitful Fun textures

### ISSUE THREAD

**Issue by Robynstar** [MehVahdJukaar/WoodGood#556] opened 2024-07-05 12:05 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.65.jar

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge.jar

### Issue with mods

Builders Crafts & Additions (Forge) - [buildersaddition-1.20.1-20230928a.jar](https://www.curseforge.com/minecraft/mc-mods/buildersaddition/files/4772826)
Macaw's Fences and Walls - [mcw-fences-1.1.2-mc1.20.1forge.jar](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls/files/5442222)
MrCrayfish's Furniture Mod - [cfm-forge-1.20.1-7.0.0-pre36.jar](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/4602980)
Quark - [Quark-4.0-458.jar](https://www.curseforge.com/minecraft/mc-mods/quark/files/5418252)

Textures
Fruitful Fun - [FruitfulFun-1.20.1-Forge-7.4.3.jar](https://www.curseforge.com/minecraft/mc-mods/fruit-trees/files/5358003)

### Issue Detail

The textures for almost all the Mr Crayfish, Builders Crafts and Quark hedges use the wrong ones:
![2024-07-05_23 38 01](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/d2484f93-6791-433c-8748-ac43fb66c725)
Mr Crayfish hedges hiding out the back, then leaf blocks, then Builders Crafts & Additions hedges, Macaw's, Quark (Quark leaf carpets at the front as they're doing the same thing)

Mr Crayfish hedges only use the correct texture for Pomegranate.
Macaw's hedges use the correct textures... there's just the Apple Oak one with the dreaded black and magenta squares. Apple Oak uses the vanilla oak leaves texture as a base, so that might be why.
For Builders Crafts and Quark, some of them (Pomegranate, Lime and Tangerine) seem to be picking up what looks to be the flower layer of the texture, and possibly an outdated version at that? (e.g. `fruitfulfun:block/tangerine_flowers` instead of `fruitfulfun:block/tangerine_leaves`) Redlove (pink set on the far left) is using the fruiting texture (`fruitfulfun:block/redlove_leaves_2`) instead of regular. The rest of them are doing something very odd!

https://github.com/Snownee/FruitfulFun/tree/c86d225ae7de2ddd808ca3ca310972163bce5e7d/src/main/resources/assets/fruitfulfun/textures/block

**Comment by Xelbayria** [comment] 2024-07-05 18:05
Pomegranate, Lime and Tangerine from **Fruitful Fun** are using incorrect textures, right?

**Comment by Xelbayria** [comment] 2024-07-05 20:10
have you used any hedge from **Quark**, if no, then I'll need to add a check for a block that the hedge from **Quark** need is a log

<strike>**FruitFul Fun** don't have logs for each leaves. </strike> Let me know if you have used them.

### EDIT:
I take what i said (the strike-through sentence) back. 

some leaves are using the log from **Fruitful Fun** but the name is not consistent. it's very troublesome. and Some are using vanilla logs like _Jungle Log_ for _Pomegranate Leaves_

**Comment by Xelbayria** [comment] 2024-07-05 23:04
Fixed and will be in **v2.6.66**, 

the problem with these hedge using the wrong texture is because of the name of the texture is all wrong. like "apple_oak_hedge" is using `oak_flowers` where it should be `oak_leaves` for texturing. Anyway, it's all fixed. 

EDIT:
forgot to mention. the recipe is fixed to use the correct logs to craft hedges from **Quark**.

**Closed as completed by Xelbayria** 2024-07-05 23:04 UTC
Labels: bug, status: done, 1.20.1-FORGE

**Comment by Robynstar** [comment] 2024-07-06 00:26
Sorry, I was asleep ;-)
But well done for untangling everything, I did think it looked like a bit of a mess.
The reason I included my hot-bar was to show that only one of the leaf blocks (redlove) actually matched its entity, to show that not even the mod itself really knows what is going on :P

**Comment by Xelbayria** [comment] 2024-07-06 03:49
no worries. The **v2.6.66** should be out on Curseforge, and have you check to see whether the issue is solved? 

> not even the mod itself really knows what is going on :P

that's true. Mod is just doing what we programmed them to do. It has no ability to think for itself to adapt.

**Comment by Robynstar** [comment] 2024-07-06 10:47
![2024-07-06_22 46 19](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/7aec70e5-4f56-41f3-8416-0441facb3c4c)
They look pretty awesome to me! :D

> that's true. Mod is just doing what we programmed them to do. It has no ability to think for itself to adapt.

Perhaps a better way I could have put it is... it would seem the mod (Fruitful Fun) is put together a little chaotically ;)
