### ISSUE TITLE
[🐞]: BrimWood Chest Texture Fail

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/WoodGood#390] opened 2024-01-10 14:10 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.16

### Moonlight Lib Version

2.3.6

### Issue with mods

RegionsUnexploredForge-0.5.3+1.19.2
Quark-3.4-418

### Issue Detail

Forge 1.19.2 Version 43.3.7
jei-1.19.2-forge-11.6.0.1018
JustEnoughProfessions-forge-1.19.2-2.0.2
JustEnoughResources-1.19.2-1.1.0.179
RegionsUnexploredForge-0.5.3+1.19.2
TerraBlender-forge-1.19.2-2.0.1.166
Quark-3.4-418
AutoRegLib-1.8.2-55
Moonlight-1.19.2-2.3.6-forge
Everycomp-1.19.2-2.5.16

I made a post on Region Unexplored on a similar topic. 
What is the problem? Initially, there are no ladders and chests for new trees in Region Unexplored. Only in this magical combination of Region Unexplored + Quark + Every Compact (Wood Good) are chests and ladders created. But there is a bug with the texture of the chest from BrimWood. 

By itself, Every Compact (Wood Good) does not add any recipes to the Region Unexplored. It's easy to check by installing only two mods and looking at the JEI. @ (Every Compact) will be empty. But when Quark is added, everything magically changes. The problem appears when adding Quark, but the recipe comes from Every Compact. 

I do not know where exactly the problem is, I think it is the relationship of 3 mods. Since the texture comes from Region Unexplored. The recipe is from Every Compact, but without Quark there will be no chests. Help me)))

![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/7f49accf-d29d-4222-b246-eb46c1f40d74)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/c4d7d535-0d63-4c7f-b9d3-e1a29e27c7bd)

### OPTIONAL: Latest.log | Crash-report Attachment

[17:00:52] [Worker-Main-4/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_trap.png not found
--
487 | [17:00:52] [Worker-Main-5/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_trap_left.png not found
488 | [17:00:52] [Worker-Main-5/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_normal.png not found
489 | [17:00:52] [Worker-Main-6/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_right.png not found
490 | [17:00:52] [Worker-Main-4/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_left.png not found
491 | [17:00:52] [Worker-Main-5/ERROR]: Using missing texture, file quark:textures/model/chest/everycompat/regions_unexplored/brimwood_trap_right.png not found

**Comment by Xelbayria** [comment] 2024-01-10 18:59
that's because brimwood is an animated texture. The only solution I can think of is to put the brimwood in your Photoshop or GIMP and turn it into a non-animated texture. Put it in a resource pack.
The details are in #356 

---

> By itself, Every Compact (Wood Good) does not add any recipes to the Region Unexplored. It's easy to check by installing only two mods and looking at the JEI. @ (Every Compact) will be empty. But when Quark is added, everything magically changes. The problem appears when adding Quark, but the recipe comes from Every Compact.

**Quark** adds chest & ladder. **Region Unexplored** is a mod that adds wood types, it wasn't supported in **Every Compat**. **Every Compat** can use **Region Unexplored** and **Quark** to create these chests and ladders.

about the recipe, you may want to check **Quark**'s configuration. **Every Compat** follows what Quark's configuration does. 

I can confirm the problem with the Brimwood texture stuff. I had no problem with recipes using 3 mods on my side. 

---
EDIT 2: 

> Every Compact (Wood Good) does not add any recipes to the Region Unexplored

**Every Compat** required 2 things: 
- Mod that adds new wood types
- Mod (supported by **Every Compat**) adds new furniture & blocks

if there are no furniture/block mods, then **Every Compat** has nothing to do. 

---
EDIT 3:

> The problem appears when adding Quark, 

hmm. I'll take a look. 

EDIT 4: 
You are right. there is nothing wrong with BrimWood texture with other furniture mods except Quark. weird. 

EDIT 5: 
after thinking about this, I got an idea of why the texture doesn't show up. This investigation will take some time.

**Comment by Krimatoria** [comment] 2024-01-18 15:19
> это потому, что Бримвуд — это анимированная текстура. Единственное решение, которое я могу придумать, — это поместить поля в Photoshop или GIMP и превратить их в неанимированную текстуру. Поместите его в пакет ресурсов. Подробности в [#356.](https://github.com/MehVahdJukaar/WoodGood/issues/356)
> 
> > Сам по себе каждый компакт (деревянный товар) не добавляет никаких рецептов в неизведанный регион. Это легко проверить, установив всего два мода и посмотрев JEI. @ (Каждый компакт) будет пустым. Но когда добавляется Quark, все волшебным образом меняется. Проблема появляется при добавлении Quark, но рецепт взят из Every Compact.
> 
> **Кварк** добавляет сундук и лестницу. **Region Unexplored** — это мод, добавляющий типы древесины, он не поддерживался в **Every Compat** . **Каждый компат** может использовать **Region Unexplored** и **Quark** для создания сундуков и лестниц.
> 
> Что касается рецепта, вы можете проверить конфигурацию Quark **. ****Каждый Compat** соответствует тому, что делает конфигурация Quark.
> 
> Я могу подтвердить проблему с текстурами Brimwood. У меня не было проблем с рецептами с использованием трех модов на моей стороне.
> 
> РЕДАКТИРОВАТЬ 2:
> 
> > Каждый компактный (деревянный товар) не добавляет рецепты в неизведанный регион.
> 
> **Для каждого Compat** требовалось 2 вещи:
> 
> * Мод, добавляющий новые виды древесины.
> * Мод (при поддержке **Every Compat** ) добавляет новую мебель и блоки.
> 
> если нет модов на мебель/блоки, то **Every Compat** делать нечего.
> 
> РЕДАКТИРОВАТЬ 3:
> 
> > Проблема появляется при добавлении Quark,
> 
> хм. Я взгляну.
> 
> РЕДАКТИРОВАТЬ 4: Вы правы. нет ничего плохого в текстуре BrimWood с другими модами на мебель, кроме Quark. странный.
> 
> РЕДАКТИРОВАТЬ 5: подумав об этом, я понял, почему текстура не отображается. Это расследование займет некоторое время.

I haven't been in for a long time. I'm glad that this can be fixed somehow)))

**Comment by Krimatoria** [comment] 2024-02-03 21:33
> that's because brimwood is an animated texture. The only solution I can think of is to put the brimwood in your Photoshop or GIMP and turn it into a non-animated texture. Put it in a resource pack. The details are in #356
> 
> > By itself, Every Compact (Wood Good) does not add any recipes to the Region Unexplored. It's easy to check by installing only two mods and looking at the JEI. @ (Every Compact) will be empty. But when Quark is added, everything magically changes. The problem appears when adding Quark, but the recipe comes from Every Compact.
> 
> **Quark** adds chest & ladder. **Region Unexplored** is a mod that adds wood types, it wasn't supported in **Every Compat**. **Every Compat** can use **Region Unexplored** and **Quark** to create these chests and ladders.
> 
> about the recipe, you may want to check **Quark**'s configuration. **Every Compat** follows what Quark's configuration does.
> 
> I can confirm the problem with the Brimwood texture stuff. I had no problem with recipes using 3 mods on my side.
> 
> EDIT 2:
> 
> > Every Compact (Wood Good) does not add any recipes to the Region Unexplored
> 
> **Every Compat** required 2 things:
> 
> * Mod that adds new wood types
> * Mod (supported by **Every Compat**) adds new furniture & blocks
> 
> if there are no furniture/block mods, then **Every Compat** has nothing to do.
> 
> EDIT 3:
> 
> > The problem appears when adding Quark,
> 
> hmm. I'll take a look.
> 
> EDIT 4: You are right. there is nothing wrong with BrimWood texture with other furniture mods except Quark. weird.
> 
> EDIT 5: after thinking about this, I got an idea of why the texture doesn't show up. This investigation will take some time.

It seems the problem is a little bigger)))) 🙈🙈🙈 @Xelbayria 
The corners of the object also have an error in texture.

![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/ae8bba1a-5cb4-4742-ad3a-c61d0e840812)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/5ed896a9-936d-4843-b768-591b178ebc02)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/e67e1710-0d63-4ca2-b903-4adcd3ebdf8c)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/9e6b05e3-24f7-462f-9717-402f92ddd0cd)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/cd0d95de-d2fb-490f-b048-7c4028433596)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/2d09a56d-a3a9-41a6-b560-702d8cd2ee98)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/b572488e-4e64-44fd-9aa4-aac494d20c87)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/0f72d0c4-943d-4cf4-959f-c03e4253661e)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/76034a76-7912-4e67-8ffe-f7e7440bd275)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/2be9a8fc-4b86-422b-ac96-040049cd1efc)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/4a0009bc-7877-425a-a018-2575361ebdb5)

**Comment by Xelbayria** [comment] 2024-02-04 04:05
are they from the same mod as _brimwood_ or a different mod?

EDIT
On another note, there is one wood I recognized _whistlecane_ (it's not a wood, it's more unique compared to bamboo). 

it has a texturing issue means it's the filename of these textures for the block's ID is not consistent. for example, if you look at the file via mod's assets: `gardens_of_the_dead:textures/block/whistle_???.png` 
take a look at the filename they have.  it doesn't have "_log" or "_stem". just "_block". that's the problem. the other hollow with texturing issues should have similar problems. 

the details regarding **Quark** and **Garden of the dead** are [here](https://github.com/MehVahdJukaar/WoodGood/issues/423#issuecomment-1924538570)
it would be good if devs of these mods can fix these filenames so they are consistent for Minecraft to use info via `model` files to find the textures for the block.

**Comment by Krimatoria** [comment] 2024-02-05 12:29
> они из того же мода, что и _Бримвуд_ , или из другого мода?
> 
> РЕДАКТИРОВАТЬ С другой стороны, есть одно дерево, которое я узнал _свистун_ (это не дерево, оно более уникально по сравнению с бамбуком).
> 
> у него проблема с текстурированием, что означает, что имя файла этих текстур для идентификатора блока не соответствует. например, если вы посмотрите на файл через ресурсы мода: `gardens_of_the_dead:textures/block/whistle_???.png` посмотрите на имя файла, которое у них есть. у него нет «_log» или «_stem». просто «_block». Это проблема. у другой полости с проблемами текстурирования должны быть аналогичные проблемы.
> 
> Подробности о **Кварке** и **Саде мертвых** здесь [.](https://github.com/MehVahdJukaar/WoodGood/issues/423#issuecomment-1924538570) Было бы хорошо, если бы разработчики этих модов могли исправить эти имена файлов, чтобы они были единообразными для Minecraft, чтобы использовать информацию из `model`файлов для поиска текстур для блока.

Я могу сделать пост и сделать ссылку на эту ветку. Это в каких модах проблема?

**Comment by Krimatoria** [comment] 2024-02-05 13:16
**Maybe these tags will help somehow)**
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/b79df78b-ecfe-4d13-bffb-4199c552043d)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/106809386/00930ca0-1d7b-43d7-ab7b-92a1214cf24f)

**Comment by Xelbayria** [comment] 2024-02-06 06:07
> Я могу сделать пост и сделать ссылку на эту ветку. Это в каких модах проблема?

as far as I know, Someone else already reported the problem to **Gardens of the Dead**. if you find mods that have similar problems like inconsistent naming for texture files and blocks' ID. You can try and let the devs of said mods know about this. 

of course, there is nothing I can do about the problem of those textures on **Every Compat**'s Side. It's very rare (not common) which is why it is unnecessary to fix this when a simple fix can be done on the mod's side.

**Comment by Xelbayria** [comment] 2024-02-06 06:11
> **Maybe these tags will help somehow)** 

The tags have a different purpose like... For example, you make a foreign wood to have a `#log`  (Can't remember what is the tag for all woods with the "log"). With the tag in one recipe to craft an item can use any logs as an ingredient. There is a lot more to how tags are used for. But it has nothing to do with textures.

**Comment by Xelbayria** [comment] 2024-02-12 08:40
Alright, about the **Born in Chaos v1**, the details are in #133 and it's already fixed with just the resource pack. For others, I'll look into them to see if I can fix them somehow. I will also apply the fix from 1.20.1 for _whistlecane_ stuff.

**Comment by Xelbayria** [comment] 2024-02-14 01:25
Brimwood texture problem is fixed in **1.20.1**, it will be in **v2.6.33** of **EveryCompat** & **v2.9.14** of **Moonlight Lib**

the same fix will be applied to 1.19.2, too.

**Closed as completed** 2024-02-14 01:27 UTC
Labels: bug, duplicate, status: done, 1.19.2-FORGE
