### ISSUE TITLE
[🐞]: Crash when entering world when 26.77

### ISSUE THREAD

**Issue by furtabs** [MehVahdJukaar/WoodGood#619] opened 2024-10-02 08:23 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.77

### Moonlight Lib Version

2.13.2

### Issue with mods

not applicable

### Issue Detail

crash on world load

### OPTIONAL: Latest.log | Crash-report Attachment

https://gist.github.com/EndangeredNayla/25408b888deed4c168625f4a05ca369d

**Comment by Xelbayria** [comment] 2024-10-02 08:34
Hmm. Can you find out which mod (supported by Every Compat) is the cause of the problem. 

It's saying the tab is null.  meaning one of the module that support the the culprit mod need to have "tab" included. 

did v2.6.76 work fine with SINYTRA CONNECTOR? if yes, then downgrade so you can play for now. 

EDIT: 
can you include `latest.log`, I want to see if i can find some clues from that file. thanks

## UPDATED: 
forget the `latest.log`, i ran into a similar issue (related to another issue aside here). If your modpack have **Beautiful Campfires**. 

Otherwise, You can use EveryCompat's Curseforge page to look at the list of supported mods to find the culprit.

**Comment by brisingraerowing** [comment] 2024-10-02 14:48
I just got this crash on game startup without Connector (or Beautiful Campfires). Will investigate further (I have a number of supported mods)

EDIT: A testing instance with all supported mods I have did not crash (with this error at least).

**Comment by Xelbayria** [comment] 2024-10-02 19:27
So You have **Beautiful Campfires** in your modpack, I've fixed the "tab" not being included via _BeauitfulCampfiresModule_.

**Comment by Xelbayria** [comment] 2024-10-03 00:29
Another one reported an issue with mod: **Another Furniture**

do you have that mod installed in the modpack? It's missing the tab stuff (will be fixed)

**Comment by Xelbayria** [comment] 2024-10-04 00:28
Let me know if the v2.6.80 solved your issue.

the following modules that don't have the tabs are: 
- Chipped
- Another Furniture (FORGE)
- Beautiful Campfires

all fixed

**Comment by LenKagamine** [comment] 2024-10-04 19:38
Crashes in 2.6.80. I think the mods are Valhelsia Furniture, Valhelsia Structures, Regions Unexplored, and Beautify

**Comment by Xelbayria** [comment] 2024-10-04 19:47
great, a few mods. I recently fixed Regions Unexplored without the tab stuff. I'll check the other and fix them if they don't have tab. 

# UPDATE
- Valhelsia Furniture don't have tab (FIXED) 
- Beautify Decorate don't have tab (FIXED)
- Valhesia Structure is fine
- Regions Unexplored (already noticed & fixed)

**Comment by Xelbayria** [comment] 2024-10-04 20:04
The fix above will be in v2.6.81

**Comment by Flappy-McJack** [comment] 2024-10-07 18:11
Hello, I'm still getting this crash when using v2.6.81 and Regions Unexplored on Minecraft version 1.20.1 Forge. It says the tab is null. My modpack is fairly large but I couldn't discern any other issues

[crash-2024-10-07_12.46.26-fml.txt](https://github.com/user-attachments/files/17282718/crash-2024-10-07_12.46.26-fml.txt)

**Comment by Xelbayria** [comment] 2024-10-07 19:11
You are correct, it was Regions Unexplored and it's fixed in v2.6.82

**Closed as completed by Xelbayria** 2024-10-07 19:11 UTC
Labels: bug, status: done, 1.20.1-FORGE
