### ISSUE TITLE
[🐞]: crash on startup upon updating Every Compat (Related to Quark)

### ISSUE THREAD

**Issue by border999** [MehVahdJukaar/WoodGood#473] opened 2024-03-29 16:46 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.40

### Moonlight Lib Version

moonlight-1.20-2.11.9-forge

### Issue with mods

Every Compat (everycomp): 1.20-2.6.40
youkaishomecoming-2.0.3
immersiveweapons-1.20.1-1.27.7
farmingforblockheads-forge-1.20.1-14.0.2
spells_and_shields-1.20.1-2.16.0
destroy-1.20.1-0.8
iceandfire-2.1.13-1.20.1-beta-4
Cognition-v2.0.3-1.20.1
Totemic-forge-1.20.1-0.12.11

### Issue Detail

Crash upon startup after updating to Everycomp-1.20-2.6.40

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-03-29_12.24.27-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14806591/crash-2024-03-29_12.24.27-client.txt)
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14806601/latest.log)

**Comment by Xelbayria** [comment] 2024-03-30 07:22
Can you isolate one mod or two mods to find which caused the crash? 

simply, disable all of the mods except **Every Compat** & **Moonlight Lib**, and enable the mods one by one until one causes the crash.

**Comment by border999** [comment] 2024-03-30 16:14
I removed all the mods above except ice and fire, a whole different slew of mods are mentioned now.
wizards_reborn-1.20.1-0.1.0
miners_delight-1.20.1-1.2.3
mna-forge-1.20.1-3.0.0.11-all (mana and artifice)
createaddition-1.20.1-1.2.3
new crash: https://gist.github.com/border999/6418db9ec11a2300e726efd578a6f8a2
Will continue removing mods until it stops dying.

**Comment by border999** [comment] 2024-03-30 16:24
This one is interesting, have you worked on Quark compatibility yet?
https://gist.github.com/border999/8c91d14c6502bbf09ccbb96be58b3339
list of mods messing up is getting shorter.
ars_nouveau-1.20.1-4.10.0-all
tetra-1.20.1-6.2.0

**Comment by border999** [comment] 2024-03-30 16:30
Cyclic-1.20.1-1.12.7 is mentioned twice in this crash.
https://gist.github.com/border999/ab397a641e12f643a5c4438917982bfc

**Comment by border999** [comment] 2024-03-30 16:36
removing Modernfix isnt helping. New crash
bloodmagic-1.20.1-3.3.2-44
https://gist.github.com/border999/ce21a5ba73c08a0b7413a1f7f4fa11ad

**Comment by border999** [comment] 2024-03-30 16:40
This one literally only has Everycomp and Moonlight listed as possible culprits mods.
https://gist.github.com/border999/3d9cbe6ab052a065cea5497a980711fb
I'm going to remove Quark and see if that solves this.

**Comment by border999** [comment] 2024-03-30 16:49
Removing Quark resolves the issue, even with every other mod back in.
Quark-4.0-439

**Comment by Xelbayria** [comment] 2024-03-31 08:23
Thanks for isolating the culprit. The investigation will be starting.

**Comment by Xelbayria** [comment] 2024-03-31 18:36
Can you make a list of wood mods and share it here? I need to find which wood mod is responsible for the crash. 

"wood mod" is a mod that adds wood variants to Minecraft. Examples: Biomes O' Plenty, The Twilight Forest, so on.

**Comment by border999** [comment] 2024-03-31 23:44
You mean like the ones I listed above for each crash?

**Comment by Xelbayria** [comment] 2024-04-01 05:14
🤔  I wasn't sure if these mods have wood variants or not. I have no time to look at these mods' descriptions via Curseforge. I'll need the list of these mods with wood variants so I can find which one caused the crash with **Quark**.

**Comment by border999** [comment] 2024-04-01 16:25
the answer is none of them. Even with all those mods removed the game still crashed when both Every Compat (everycomp): 1.20-2.6.40 and Quark-4.0-439 try to load together. Quark has wood variants. Look at quark.

**Comment by Xelbayria** [comment] 2024-04-01 18:18
Strange. I ran tests with just **Quark**, **EveryCompat**, **Moonlight Lib**, 
and **Zeta** (**Quark** is dependent on) to run. and it was all fine. 

Do u have **Zeta** installed?

**Comment by MehVahdJukaar** [comment] 2024-04-01 19:07
If you just install quark and ec the game will crash because no wood mod is installed (quark is one but none of its blocks need to be registered)

**Comment by border999** [comment] 2024-04-02 10:16
Don't know what to tell you. Threw every crash log I got while pulling out mods in this issue chain. Until I found yaning Quark made the crashing stop. Shall I also list off the three addons for Quark I was using that I also pulled because I was removing Quark?
![image](https://github.com/MehVahdJukaar/WoodGood/assets/11824584/63a4c622-159e-4482-8486-4f1ad6c8a6ea)

**Comment by Kahzel** [comment] 2024-04-06 18:11
To add to the investigation, I am experiencing the same crash. Alongside Quark, I also have the following wood mods installed which Every Compat supports:

<details>

Ad Astra 1.15.18
Aether Redux 2.0.8-1.20.1
Alex's Caves 1.1.4
Ars Noveau 4.9.0
Born in Chaos 1.0.0
Beachparty 1.1.4-1
Create: Diesel Generators 1.20.1-1.2h
Create: Dreams & Desires 1.20.1-0.2c.PREBETA
Deep Aether 1.20.1-1.0.2
Deeper and Darker 1.2.1
Enlightened 5.0.14
Feywild 1.20.1-4.0.1
Forbidden and Arcanus 1.20.1-2.2.6
Meadow 1.3.7
Outer End 1.0.8
Regions Unexplored 0.5.5+1.20.1
The Aether 1.20.1-1.3.1-neoforge
Twilight Forest 4.3.2145
Unusual Prehistory 1.5.0.3

</details>

That being said, Feywild was added after I started experiencing the crashes, so I would rule it out. This happens with these mods and Every Compat >= 1.20-2.6.40. Using forge version 1.20.1-47.2.17 as well.

**Comment by Xelbayria** [comment] 2024-04-06 22:55
Can i get the crash-report. i want to take a look and may able to find out why the crash happened.

**Comment by Kahzel** [comment] 2024-04-07 16:04
Here's both the debug.log and the crash-report.
[debug.log](https://github.com/MehVahdJukaar/WoodGood/files/14897864/debug.log)
[crash-2024-04-07_12.03.01-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14897865/crash-2024-04-07_12.03.01-client.txt)

**Comment by Xelbayria** [comment] 2024-04-07 20:46
<details>

1. Ad Astra 1.15.18
2. Aether Redux 2.0.8-1.20.1
3. Alex's Caves 1.1.4
4. Ars Noveau 4.9.0
5. Born in Chaos 1.0.0
6. Beachparty 1.1.4-1
7. Create: Diesel Generators 1.20.1-1.2h
8. Create: Dreams & Desires 1.20.1-0.2c.PREBETA
9. Deep Aether 1.20.1-1.0.2
10. Deeper and Darker 1.2.1
11. Enlightened 5.0.14
12. Feywild 1.20.1-4.0.1
13. Forbidden and Arcanus 1.20.1-2.2.6
14. Meadow 1.3.7
15. Outer End 1.0.8
16. Regions Unexplored 0.5.5+1.20.1
17. The Aether 1.20.1-1.3.1-neoforge
18. Twilight Forest 4.3.2145
19. Unusual Prehistory 1.5.0.3

</details>

Can you disable all of wood mods. and enable them one by one. until you get the crash. I need to know which wood mod is causing "null" from Quark Module.

**Comment by Kahzel** [comment] 2024-04-08 03:52
[debug.log](https://github.com/MehVahdJukaar/WoodGood/files/14900600/debug.log)
[crash-2024-04-07_23.41.15-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14900601/crash-2024-04-07_23.41.15-client.txt)

Removed all the aformentioned mods, as well as enough mods to make it so that the only time Every Compat would attempt to register items would be if quark was installed. It will crash no matter what, so long as Quark is enabled.

So, to answer "which wood mod is causing null from Quark module", it might be Quark itself. 
![image](https://github.com/MehVahdJukaar/WoodGood/assets/16464617/027480ba-c78e-4404-8b02-8d4c275df3d6)

![image](https://github.com/MehVahdJukaar/WoodGood/assets/16464617/5d09f667-65d0-4d5b-9da3-07365b603eae)
Quark adds three wood types: Ashen (ancient), Azalea and Trumpet (blossom). These are supported by Every Compat. Perhaps it has something to do with the mod trying to create items from the Quark module using Quark's woods?

**Comment by Xelbayria** [comment] 2024-04-08 04:13
hmm. The version of **Quark** is Quark-4.0-439.jar and the **Zeta** is Zeta-1.0-14.jar? 

Try to delete them and download them again (should be a clean mod). And do the same with **EveryComp**.  I wasn't able to replicate the crash on my side.

**Comment by Kahzel** [comment] 2024-04-08 04:45
Yes.
That being said, I made a fresh instance with only everycomp, quark and their dependencies (moonlight and zeta) on their latest versions and it did not crash. Added the "provider" mods I have on my normal instance (Farmer's Delight, Chipped, Furnish, etc) no crashes.

Went back to my normal instance, took the Quark config files out so they would be recreated, did not crash. 

Had a look at the diff for both files, the differences between this file (which was causing crashes) and the default that's generated when there is no quark-common config file is almost nothing (extension renamed from .toml to .txt so i could upload).
[quark-common.txt](https://github.com/MehVahdJukaar/WoodGood/files/14900991/quark-common.txt)

Need to go bed now since It's pretty late here now, but I will see if i can find out more tomorrow.

**Comment by Xelbayria** [comment] 2024-04-08 04:52
I'll use that `quark-common.toml` and see if I can replicate the crash. 

### UPDATE: 
wasn't able to replicate the crash. Use v2.6.45 (currently awaiting approval) and give me the crash report & latest.log. Some logging are added to the code so hopefully that will help us find out what's going on.

**Comment by Kahzel** [comment] 2024-04-08 13:15
I can't seem to replicate the crash again on my main instance. Removing `quark-common.toml` and letting it be re-created seems to have fixed it.

**Comment by Xelbayria** [comment] 2024-04-08 18:02
I see. looks like it was a corrupted configuration file.

**Comment by border999** [comment] 2024-04-08 19:47
Tried the above fix, still crashing. Updated to v2.6.45, here's the logs.
https://gist.github.com/border999/6a2ac4e7531146915844c38efcb7fad0 -crash
https://gist.github.com/border999/47b0a194b6f660d61497a26976217646 -latest.log

**Comment by Xelbayria** [comment] 2024-04-08 20:49
have you deleted the config file? Quark will create a new one when it's missing.

**Comment by border999** [comment] 2024-04-08 23:20
yes. I deleted the configs for EveryComp, Quark, Zeta, and moonlight.

**Comment by border999** [comment] 2024-04-08 23:46
Updated to v2.6.46
https://gist.github.com/border999/d840b6fda9e95311b398b11a12c45116 -latest.log
https://gist.github.com/border999/71bef8b30ec8f1891d8b7459895c6922 -crash

**Comment by Xelbayria** [comment] 2024-04-09 06:19
Can you create a simple instance with just **Quark**, **Zeta**, **EveryComp**, **Moonlight Lib**, and any wood mods of your choice? Run it and check if the simple list can cause a crash.

**Comment by border999** [comment] 2024-04-09 14:55
IT'S JAOPCA-1.20.1-4.4.10.15! I just took the last hour or so slowly spoon feeding mods back into my pack until I got the crash. Finally found the damn mod that when I pull it lets everything else work.

**Comment by MehVahdJukaar** [comment] 2024-04-09 15:21
if this just happens with only a new version of another mod and works without then its likely their issue and shuld be contacted

**Comment by border999** [comment] 2024-04-09 16:21
https://github.com/TheLMiffy1111/JAOPCA/issues/300

**Comment by MehVahdJukaar** [comment] 2024-04-09 17:04
so i tested with that mod, EC, quark and a couple other mods on 1.20.1 and game boted up fine

**Comment by border999** [comment] 2024-04-09 22:33
at this point... seems like it's a bug between so many mods that it'll take quite some time to untangle. Do you wish to continue looking down the rabbit hole? I can start my mod adding again, this time starting with EC, moonlight, quark, JAOPCA, and Zeta.

**Comment by MaxWasUnavailable** [comment] 2024-04-10 20:52
Just a shot in the dark, but could all of you who are running into issues try increasing your allocated RAM and see if that resolves it? I'm running into a virtually the same crash report with some users of my modpack. The difference *seems* to be RAM allocation. I run my modpack with 12 GB, as do some others, and it works fine. People that are running it with less than 12GB are running into this crash, however.

You may need to wipe the config folder / do a clean install *before* running it, to prevent the initial crash.

**Comment by border999** [comment] 2024-04-11 03:20
I have my arguments set so that I have 16GB available.

**Comment by MaxWasUnavailable** [comment] 2024-04-25 18:03
I've done a deep dive in my modpack, and it seems this mod specifically is responsible for the crash. The last version where this crash doesn't occur for us is `everycomp-1.20-2.6.39`.

**Comment by MaxWasUnavailable** [comment] 2024-04-25 18:07
Seems like it might be something that happened between these two commits: https://github.com/MehVahdJukaar/WoodGood/compare/94b6e8f..634cc64

(Version .39 compared to .40)

@Xelbayria @MehVahdJukaar

**Comment by Xelbayria** [comment] 2024-04-25 19:09
Do you have a potato PC?  I've heard that high-end PC users have no problem with **Quark** and the latest version of **EveryComp** in the Modpack. But potato PC users have problems with **Quark** & **EC**.

**Comment by MaxWasUnavailable** [comment] 2024-04-25 19:14
> Do you have a potato PC? I've heard that high-end PC users have no problem with **Quark** and the latest version of **EveryComp** in the Modpack. But potato PC users have problems with **Quark** & **EC**.

No, I personally have a high-end PC (basically maxed out AM4 platform), and I *can* load the latest version of EveryComp in this modpack.

That being said, there's clearly *something* going wrong in the mod, considering the crash is not deterministic, and dependent on PC specs - and not related to out of memory errors (we tested this fairly thoroughly).

Users with potato PCs can reliably load the pack with version .39 of EveryComp, even with *all* other mods updated. Once they update EveryComp to any version above .39, the crash issue manifests (relatively reliably, depending on the user's PC specs being low enough).

**Comment by Xelbayria** [comment] 2024-04-26 07:26
You'll need to disable all of the mods supported by **EveryComp** and enable them one by one until one causes the crash. The only reasons why the crash happened are because: 
1) one of the supported mods is updated to the latest with minor changes (yes it can cause a crash in some case)
2) One of the mods isn't updated to the latest version (it's supported by the latest version of **EveryComp**)
    - Check Macaw's mods if you have them and ensure they are updated to the latest
    - Check Workshop for Handsome's version
3) If you have **MrCrayFish Refurbished Furniture**, then check if you have the latest version. IIRC the latest version is _beta-4_

either one of these is the reason why a crash happened. Between 39 and 40 of EveryComp, there are some changes to the supported mods to support the latest version of the mod.

**Comment by MaxWasUnavailable** [comment] 2024-04-26 12:48
> You'll need to disable all of the mods supported by **EveryComp** and enable them one by one until one causes the crash. The only reasons why the crash happened are because:
> 
>     1. one of the supported mods is updated to the latest with minor changes (yes it can cause a crash in some case)
> 
>     2. One of the mods isn't updated to the latest version (it's supported by the latest version of **EveryComp**)
>        
>        * Check Macaw's mods if you have them and ensure they are updated to the latest
>        * Check Workshop for Handsome's version
> 
>     3. If you have **MrCrayFish Refurbished Furniture**, then check if you have the latest version. IIRC the latest version is _beta-4_
> 
> 
> either one of these is the reason why a crash happened. Between 39 and 40 of EveryComp, there are some changes to the supported mods to support the latest version of the mod.

This doesn't seem to make sense, considering people with beefy PCs can load and run the pack fine, and use the blocks reported in the crash logs without crashing. Only people with slower PCs are running into problems at modpack boot.

Is it possibly related to your [ExtraTextureGenerator](common/src/main/java/net/mehvahdjukaar/every_compat/dynamicpack/ExtraTextureGenerator.java)?

**Comment by Xelbayria** [comment] 2024-04-26 18:23
IIRC, `ExtraTextureGenerator.java` never changed between 39 and 40 of **EveryComp**. Even if it is changed, it shouldn't have caused a crash because it's just responsible for generating textures.  if it failed to generate a texture, then it would log with "error" in the latest.log

> This doesn't seem to make sense

That's why I labelled this "investigation" because I have no clue.

**Comment by MaxWasUnavailable** [comment] 2024-04-26 22:58
> IIRC, `ExtraTextureGenerator.java` never changed between 39 and 40 of **EveryComp**.

Please see the following commit comparison: https://github.com/MehVahdJukaar/WoodGood/compare/94b6e8f...634cc64

It was seemingly added in this commit: https://github.com/MehVahdJukaar/WoodGood/commit/80fa5e67540cc805769e86e0eedaf034e7c62f9f

That commit was before the version was incremented to .40

> That's why I labelled this "investigation" because I have no clue.

Well, all I can point you towards is that something in that commit list might be at fault. Users can boot up the pack fine on version 39. Any version beyond that causes an inconsistent crash on boot for users with lower spec PCs.

**Comment by Xelbayria** [comment] 2024-04-27 00:11
ok... let me clarify what I said in my previous message: 

>  it shouldn't have caused a crash because it's just responsible for generating textures. if it failed to generate a texture, then it would log with "error" in the latest.log

What I mean is that the generation of textures can't cause a crash. even generation of texture failed, it won't cause a crash. the error will get logged in `latest.log`. It's irrelevant. 

a few causes that can cause a crash is: 
1) EC can't find the required block from the mod and use it as a reference
2) failing to register a block on the mod's side or EC's side. 
3) rendering system can be incorrect and lead to crash
4) a few more that I haven't covered. 

> You'll need to disable all of the mods supported by EveryComp and enable them one by one until one causes the crash. 

you should do above. if you don't wish to spend your time on this. that's fine. the investigation is still ongoing.

**Comment by MaxWasUnavailable** [comment] 2024-05-01 16:02
> ok... let me clarify what I said in my previous message:
> 
> > it shouldn't have caused a crash because it's just responsible for generating textures. if it failed to generate a texture, then it would log with "error" in the latest.log
> 
> What I mean is that the generation of textures can't cause a crash. even generation of texture failed, it won't cause a crash. the error will get logged in `latest.log`. It's irrelevant.
> 
> a few causes that can cause a crash is:
> 
>     1. EC can't find the required block from the mod and use it as a reference
> 
>     2. failing to register a block on the mod's side or EC's side.
> 
>     3. rendering system can be incorrect and lead to crash
> 
>     4. a few more that I haven't covered.
> 
> 
> > You'll need to disable all of the mods supported by EveryComp and enable them one by one until one causes the crash.
> 
> you should do above. if you don't wish to spend your time on this. that's fine. the investigation is still ongoing.

All of the crash causes you mention should be deterministic. The fact people with faster PCs can load the exact same modpack, with the exact same mods, config, Java version/flavor, same amount of allocated RAM, and same generation of GPU (in our testing) seems to imply the issue is something non-deterministic (e.g. the game or mod perhaps loading things off-thread, and expecting it at some point in time when slower PCs can't get it ready fast enough?). I'm not sure why you flagged the investigating I did as off-topic, since I've verified on our end that it's reliably something that changed / was added between version .39 and .40 that causes the crash for slower PCs.

Faster PCs that manage to load the pack can use the blocks / variants properly, even ones that are reported in the crash report of slower PCs.

**Comment by MehVahdJukaar** [comment] 2024-05-01 16:42
can i get a minimum mod list required to replicate this? also check all the related mods are updated and see if it still happens

**Comment by Xelbayria** [comment] 2024-07-16 20:38
Any progress on this issue?

**Comment by MaxWasUnavailable** [comment] 2024-07-16 22:37
We removed WoodGood/EveryCompat from the pack, since that fixed the issues for all of our players. Mods were all up-to-date at the time of the report, for what it's worth.

**Comment by Xelbayria** [comment] 2024-07-16 23:48
Okay, now it's resolved. I'll close this. Thanks for replying. 

FYI, having too many wood mods (**Biomes O' Plenty**, **The Twilight Forest** so on...) can cause a high usage of RAM. I've got a similar report from a guy who is hosting a server. He ended removing **EveryComp**. 

Take care!

**Closed as not planned by Xelbayria** 2024-07-16 23:48 UTC
Labels: 1.20.1-FORGE
