### ISSUE TITLE
Macaw's Roofs 2.2.4 breaks WoodGood

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#192] opened 2023-06-15 21:47 UTC
Relevant error from log:

```text
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.11.jar%231084!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.11.jar%231083!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchFieldError: ROOFSITEMGROUP
	at net.mehvahdjukaar.every_compat.modules.forge.mcaw.MacawRoofsModule.<init>(MacawRoofsModule.java:44) ~[everycomp-1.19.2-2.4.9a.jar%23786!/:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:132) ~[everycomp-1.19.2-2.4.9a.jar%23786!/:?]
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.<init>(EveryCompatForge.java:98) ~[everycomp-1.19.2-2.4.9a.jar%23786!/:?]
	... 14 more
```

**Comment by TheFighter137** [comment] 2023-06-16 16:35
I have the exact same issue, but here are my complete logs : https://mclo.gs/IKuL48b (the lines to look at are probably between 683 and 703)
I checked every single mod, and Macaw's Rooves is indeed the only one messing things up with Every Compat ; if I disable one of them, the other works well
The issue is probably cause to the fact that since the last EveryCompat update (May 31st), a new version of Macaw's Rooves appeared yesterday , so the former would need an update probably

**Comment by KostromDan** [comment] 2023-06-19 01:01
same
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/11783064/latest.log)
[crash-2023-06-19_03.59.16-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11783065/crash-2023-06-19_03.59.16-fml.txt)

**Comment by MehVahdJukaar** [comment] 2023-06-29 14:46
should be fixed

**Comment by Xelbayria** [comment] 2023-10-13 03:26
Friendly Remind: If the problem is resolved, then please close this, thanks!

**Closed as completed** 2023-10-13 13:52 UTC
Labels: bug, status: done
