### ISSUE TITLE
[🐞]: Alex's Caves wood types have no compat blocks

### ISSUE THREAD

**Issue by dabomb6405** [MehVahdJukaar/WoodGood#319] opened 2023-10-31 21:09 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.15

### Moonlight Lib Version

2.8.51

### Issue with mods

Alex's Caves 1.0.6

### Issue Detail

The Pewen and Thornwood wood types from Alex's Caves don't have any compat blocks created.

**Comment by Xelbayria** [comment] 2023-11-01 01:13
Can you check if these woods from **Alex's Caves** have the "Bass" sound? If they all have it, then does **Alex's Caves** have a normal format ID for woods like
- `minecraft:oak_log`
- `minecraft:oak_planks`
- `minecraft:oak_wood`
so on. 

A good example from the mod with a unique ID: **TerraFiramcraft (1.18.2)**
- `tfc:wood/log/oak`
- `tfc:wood/planks/oak`
- `tfc:wood/wood/oak`

**Comment by dabomb6405** [comment] 2023-11-01 03:22
I just tested, and the Alex's Caves woods do not use the Bass sound. They do follow the ID format though.

**Comment by Xelbayria** [comment] 2023-11-01 03:46
Alright. you need to let the author of that mod know that his woodblock needs to have a "Bass" sound. that's the cause of the problem. Every Compat detects wood by using sounds that have the "Bass".

**Comment by MehVahdJukaar** [comment] 2023-11-01 10:51
If they use some other sound other than stone one then I'll broaden the wood detection but in most cases missing or incorrect noteblock sounds is 99% unintended and a bug where authors just forget to assign them

**Comment by ambientNexus** [comment] 2023-11-11 22:43
The issue had been fixed in version 1.0.7 of Alex's caves, this can be closed now.

**Closed as completed** 2023-11-11 23:27 UTC
Labels: not-related, 1.20.1-FORGE
