### ISSUE TITLE
[BUG][Fabric] Crash when trying to display the creative inventory tab (1.20)

### ISSUE THREAD

**Issue by RMEngelbrecht** [MehVahdJukaar/WoodGood#237] opened 2023-08-25 13:45 UTC
Whenever I cycle through my creative inventory tabs to a page that includes the Every Compat (Wood Good) tab the game crashes due to an arithmetic exception.

I'm on v1.20-2.6.3 of the mod, on Minecraft 1.20(.1), here is the crashlog of the crash:
[crash-2023-08-25_15.37.47-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/12439997/crash-2023-08-25_15.37.47-client.txt)

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:41
Uninstall every compat. You don't need it

**Comment by sneetsnart** [comment] 2023-10-05 11:02
i seem to be having the same issue, quilt 1.19.2 version 1.19.2-2.5.9 of every compat. 

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/12817572/latest.log)

**Comment by MehVahdJukaar** [comment] 2023-10-05 14:49
Same issue same asnwer

**Comment by Xelbayria** [comment] 2023-10-07 06:53
If the issue is not relevant to Every Compat, then please close this issue.

**Closed as completed** 2023-10-09 17:59 UTC
