### ISSUE TITLE
[🐞]: 1.20.1 Forge - Crash on server startup

### ISSUE THREAD

**Issue by vivagabe** [MehVahdJukaar/WoodGood#521] opened 2024-06-04 06:52 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.57

### Moonlight Lib Version

1.20-2.11.31

### Issue with mods

QUAD (MCV dependency) 
[crash-2024-06-03_18.55.28-fml.txt](https://github.com/user-attachments/files/15543670/crash-2024-06-03_18.55.28-fml.txt)

### Issue Detail

Server crashes on start.
[latest.log](https://github.com/user-attachments/files/15543689/latest.log)

**Comment by Xelbayria** [comment] 2024-06-04 17:33
Strange. I had no problem on my side. Can you do a test by isolating the following: 
- EveryComp
- Moonlight Lib
- Quad
- MoreChestVariant
- Wood mod of your choice (Biomes O' Plenty or other) 

let me know if you run into a problem.

**Comment by PanIntegrah** [comment] 2024-06-05 03:08
> Strange. I had no problem on my side. Can you do a test by isolating the following:
> 
>     * EveryComp
> 
>     * Moonlight Lib
> 
>     * Quad
> 
>     * MoreChestVariant
> 
>     * Wood mod of your choice (Biomes O' Plenty or other)
> 
> 
> let me know if you run into a problem.

Probably a problem with "More Chest Variants", as I tried launching a server with these mods, it crashed, then removed "MCV", and it worked.

**Comment by Xelbayria** [comment] 2024-06-05 03:14
@PanIntegralus U are using the latest version for all of these mods, right?   You gotta make sure that both Client & Server are using the same version and also Forge Version, too.

**Comment by Xelbayria** [comment] 2024-06-05 03:16
@MehVahdJukaar 
i could use your help with this. Idk where is the problem. Take a look at the crash-report file. 

via Crash-Report: `java.lang.NoClassDefFoundError: net/minecraft/client/renderer/blockentity/BlockEntityRenderer`
it's quite strange.

**Comment by PanIntegrah** [comment] 2024-06-05 03:25
> @PanIntegralus U are using the latest version for all of these mods, right? You gotta make sure that both Client & Server are using the same version and also Forge Version, too.

Yep, also I got the same error as OP.

**Comment by Epig-is-a-llama** [comment] 2024-06-08 01:53
I had an identical issue, (also forge, 1.20.1 and latest mod version), the dedicated server crashed rapidly on launch with the crash report attributing it to the mod; downgrading the mod to `2.6.56` eliminated the issue and the server loaded without incident.

**Comment by vivagabe** [comment] 2024-06-08 05:31
Are the chest craftable in that version? I think that version of Every Compat had a bug where the chest didn't have a recipe.

**Comment by Xelbayria** [comment] 2024-06-08 07:11
@vivagabe is correct. **MCV** don't have the recipe in **v2.6.56**. it was fixed in **v2.6.57**. tbh, it's not a bug. I forgot to add the said recipes for **MCV**.

Anyway, the investigation is still ongoing. 

UPDATE:
can you try **v2.6.58** and if the server crashed. please give me the files (Crash-report & latest.log). thanks

EDIT: 
did you get the mod from Modrinth?

**Comment by vivagabe** [comment] 2024-06-08 08:01
Ah bummer. still a crash: 
[crash-2024-06-08_01.00.27-fml.txt](https://github.com/user-attachments/files/15747248/crash-2024-06-08_01.00.27-fml.txt)

I got MCV and QUAD from modrinth and every compat on curseforge.

**Comment by vivagabe** [comment] 2024-06-08 08:02
[latest.log](https://github.com/user-attachments/files/15747252/latest.log)

**Comment by Xelbayria** [comment] 2024-06-08 10:05
tsk. we'll have to wait for MehVahdJukaar. Idk why the required class (a file) is not found on the Server side. It was working fine on the Client side. IIRC where the 3 mods: MCV, Woodworks, and Variant Vanilla Blocks all have been updated in 2.6.57 to use the same class for rendering _chest_ or _trapped_chest_. It may be related to that. 

### UPDATE
I ran a test with **Variant Vanilla Block** on the Server side, and I got the same error.

**Comment by vivagabe** [comment] 2024-06-08 10:15
Ah ok. thanks for all the help. hopefully will be resolved.

**Comment by Epig-is-a-llama** [comment] 2024-06-08 17:38
> Are the chest craftable in that version? I think that version of Every Compat had a bug where the chest didn't have a recipe.

From my very crude and limited testing the few chests I checked appear to lack texture but still appear craftable (trapped chests lacked texture and recipe), quite honestly I will take a few buggy textures for a few days if it means the server can actually start...

Singleplayer works just fine with `2.6.57` (yet to test `2.6.58`) both with existing and newly-created worlds, but it appears that the crash is something specifically limited to dedicated servers.

**Comment by Xelbayria** [comment] 2024-06-08 23:22
reason; accidentally added "done" in the wrong issue. 

---

## UPDATE: 
Good news. This bug is fixed. and will be in **v2.6.59**

Plus the fix will be applied to the other 2 modules that use the same common_classes

**Closed as completed** 2024-06-08 23:37 UTC
Labels: bug, status: done, 1.20.1-FORGE, server

**Comment by SdeSpencer** [comment] 2024-08-09 21:06
Issue has reappeared (At least for Woodworks) in the newest version. 
[latest.log](https://github.com/user-attachments/files/16566900/latest.log)

**Comment by Xelbayria** [comment] 2024-08-10 04:50
It's already fixed in v2.6.71
