### ISSUE TITLE
[1.20] Snowblossom hedge doesn't have a texture

### ISSUE THREAD

**Issue by vinnyg0621** [MehVahdJukaar/WoodGood#276] opened 2023-10-11 17:27 UTC
<img width="441" alt="Screenshot 2023-10-10 142729" src="https://github.com/MehVahdJukaar/WoodGood/assets/57818441/3a5d2759-6682-4c92-b16f-0bf16cca03b8">

Minecraft version: 1.20.1
Loader: Forge
EveryCompat version: latest
Mods that EC has an issue with:

- Biomes O'Plenty
- Macaw's fences & walls

**Comment by Xelbayria** [comment] 2023-10-13 03:34
please fill in the following:
Minecraft Version: 1.20.1
Loader: (Forge or Fabric)
EveryCompat (EC) Version:
Which Mods does EC have an issue with:
- Biomes O' Plenty
- and which mod that give the hedge

**Comment by stlouisn** [comment] 2023-11-28 15:08
Minecraft Version: 1.20.1
Loader: Forge 47.2.1
EveryCompat (EC) Version: 1.20-2.6.18
Which Mods does EC have an issue with:

Leaf from: Biomes O' Plenty: biomesoplenty:blossom_leaves
Hedge from: Macaw Fences: everycomp:mcf/biomesoplenty/snowblossom_hedge

Minecraft Log:

`[Worker-ResourceReload-3/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:mcf/biomesoplenty/snowblossom_hedge#east=tall,north=none,south=tall,up=true,waterlogged=true,west=low:
    minecraft:textures/atlas/blocks.png:everycomp:block/mcf/biomesoplenty/snowblossom_hedge`

`[Worker-ResourceReload-3/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:mcf/biomesoplenty/snowblossom_hedge#inventory:
    minecraft:textures/atlas/blocks.png:everycomp:block/mcf/biomesoplenty/snowblossom_hedge`

**Comment by Xelbayria** [comment] 2024-02-09 00:44
I ran tests with these: 
- Biomes O'Plenty
- Macaw's fences & walls

the issue is fixed. closing this

**Closed as completed by Xelbayria** 2024-02-09 00:44 UTC
Labels: bug, 1.20.1-FORGE
