### ISSUE TITLE
[🐞]: Advent of Ascension - Stranglewood

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#698] opened 2024-11-26 05:20 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1 - FORGE

### EveryCompat Version

2.6.92

### Moonlight Lib Version

2.13.30

### Issue with mods

Advent of Ascension 3.7.1
https://modrinth.com/mod/adventofascension

### Issue Detail

Stranglewood blocks have no textures and no models
![2024-11-26_00 19 55](https://github.com/user-attachments/assets/d42e773a-6a82-4c82-82c3-9f2b81a25eef)
![2024-11-26_00 20 09](https://github.com/user-attachments/assets/ae01651a-69f5-4870-a783-ea74a60d4bc8)

**Comment by Xelbayria** [comment] 2024-11-26 05:22
\<deleted\> 

BTW, you forgot to select **Version - Loader**, don't worry about it. I edited it to use 1.20.1-FORGE

---

EDIT: 
nvm. It's not the filename or path texture. I looked at the latest.log. For some reason, EveryComp wasn't able to copy the model for Stranglewood.

**Comment by Xelbayria** [comment] 2024-11-26 05:41
Ok. The issue is on **Advent Of Ascension**, it need to be fixed by the dev. 

I'll explain why. 

the model of 

<details>
<summary>stranglewood_log.json</summary>

{
  "parent": "minecraft:block/block",
  "elements": [
    {
      "faces": {
        "down": {
          "cullface": "down",
          "texture": "#down"
        },
        "east": {
          "cullface": "east",
          "texture": "#east"
        },
        "north": {
          "cullface": "north",
          "texture": "#north"
        },
        "south": {
          "cullface": "south",
          "texture": "#south"
        },
        "up": {
          "cullface": "up",
          "texture": "#up"
        },
        "west": {
          "cullface": "west",
          "texture": "#west"
        }
      },
      "from": [
        0,
        0,
        0
      ],
      "to": [
        16,
        16,
        16
      ]
    },
    {
      "faces": {
        "down": {
          "cullface": "down",
          "texture": "#vine_top",
          "tintindex": 0
        },
        "east": {
          "cullface": "east",
          "texture": "#vine_side",
          "tintindex": 0
        },
        "north": {
          "cullface": "north",
          "texture": "#vine_side",
          "tintindex": 0
        },
        "south": {
          "cullface": "south",
          "texture": "#vine_side",
          "tintindex": 0
        },
        "up": {
          "cullface": "up",
          "texture": "#vine_top",
          "tintindex": 0
        },
        "west": {
          "cullface": "west",
          "texture": "#vine_side",
          "tintindex": 0
        }
      },
      "from": [
        0,
        0,
        0
      ],
      "to": [
        16,
        16,
        16
      ]
    }
  ],
  "render_type": "minecraft:cutout_mipped",
  "textures": {
    "down": "#end",
    "east": "#side",
    "end": "aoa3:block/stranglewood_log_top",
    "north": "#side",
    "particle": "#side",
    "side": "aoa3:block/stranglewood_log",
    "south": "#side",
    "up": "#end",
    "vine_side": "aoa3:block/stranglewood_log_vine",
    "vine_top": "aoa3:block/stranglewood_log_top_vine",
    "west": "#side"
  }
}

</details>

The other logs look like this: 

<details>
<summary>[WOODTYPE]_log.json</summary>

{
  "parent": "minecraft:block/cube_column",
  "render_type": "minecraft:solid",
  "textures": {
    "end": "aoa3:block/shadow_log_top",
    "side": "aoa3:block/shadow_log"
  }
}

</details>

_stranglewood_log_'s json need to be changed to the one above [WOODTYPE]_log.json. it's not much of work for the DEV to fix. the model of stranglewood_log.json is why EveryComp couldn't copy or read the model. That's what the latest.log pointed out.

**Comment by Xelbayria** [comment] 2024-11-26 05:48
nvm. 

<strike>you should ask the Dev's option about what I said above. I understand why `stranglewood_log` has a model file like that. it was meant to use 2 different texture: using wood and using vines.

If the dev could adapt the method from **Ecologics**'s flowering_azalea, it used 2 textures similar to stranglewood_log but the method is different that achieve the same goal. 

Let me know what Dev's thought on this. 
</strike>

### UPDATED: 

FIXED. but the log stuff won't have the vines part applied. You don't have to speak to DEV

**Comment by Xelbayria** [comment] 2024-11-26 07:27
## FIXED IN v2.6.93

**Closed as completed by Xelbayria** 2024-11-26 07:27 UTC
Labels: bug, 1.20.1-FORGE
