### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by BlackAures1** [MehVahdJukaar/WoodGood#162] opened 2023-04-24 13:52 UTC
[crash-2023-04-24_16.42.46-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11311154/crash-2023-04-24_16.42.46-fml.txt)

All detail here. Modpack Play as dragon

**Comment by TJT01** [comment] 2023-04-24 18:22
Duplicate of https://github.com/MehVahdJukaar/WoodGood/issues/160

**Closed as completed** 2023-04-28 17:05 UTC
