### ISSUE TITLE
[🐞]: "Missing Wilds" and "Backpacked" interacting with "End's Phantasm" through EveryCompat errors

### ISSUE THREAD

**Issue by sheshells** [MehVahdJukaar/WoodGood#554] opened 2024-07-04 05:58 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-1.6.12

### Moonlight Lib Version

selene-1.18.2-1.17.14

### Issue with mods

Missing Wilds v1.1.0 (Latest release as of writing)
End's Phantasm v1.2.10.5 (Latest release as of writing)
Backpacked v2.1.13

### Issue Detail

Note: this issue is similar to [#589](https://github.com/MehVahdJukaar/WoodGood/issues/529)

![2024-07-04_00 54 37](https://github.com/MehVahdJukaar/WoodGood/assets/156608496/ff914e17-7eb8-4499-b660-a5a4af960cbc)

The mod "End's Phantasm" includes log-like items called "Ebony Stem" and "Ebony Packed Stems" and their stripped counterparts. EveryCompat is correctly trying to create a "Fallen Log" variant of these blocks, an addition from the mod "Missing Wilds."

The issue is likely multifaceted:
 1. EveryCompat is trying to refer to "phantasm:ebony_stem" through "everycomp:msw/phantasm/fallen_ebony_log", note the mismatch of "stem" and "log."
 2. End's Phantasm's "Ebony Stem" and "Stripped Ebony Stem" are both _not_ full blocks, which may result in any code trying to grab textures missing three fourths of its expected texture pulls. This _could_ be solved by trying to grab the "Ebony Packed Stems" and "Stripped Ebony Packed Stems" textures for the Missing Wilds compat (but I don't know exactly how y'all generate these items).

Secondarily (and perhaps would be its own bug report but I'm saving some hassle sorry):

The mod "Backpacked" includes backpack shelves, which are shelves similar in texture to their corresponding planks. End's Phantasm's Ebony wood type is incorrectly rendered as the oak planks texture (likely as a failsafe I presume?).

I do not have any suggestions on why this second half of this report is occurring, I'm sorry. My only guess is that it has something in common with the above issue, hence its inclusion here.

**Comment by Xelbayria** [comment] 2024-07-04 07:12
hmm. 🤔 It's possible to fix this. I need to take a look at the problem to know what's the cause and apply the fix. 

### UPDATE: 

I see the problem. I can fix the displaying title from "log" to "Stem".

**Comment by Xelbayria** [comment] 2024-07-04 08:21
Fixed.  will be in **v1.6.13** and the fix is also applied to **Selene v1.17.15**

both will be upload to Curseforge/Modrinth later

**Closed as completed by Xelbayria** 2024-07-04 08:21 UTC
Labels: bug, status: done, 1.18.2
