### ISSUE TITLE
[🐞]: latest update 2.7.4 crashes on loading

### ISSUE THREAD

**Issue by BurningSulphur** [MehVahdJukaar/WoodGood#721] opened 2024-12-16 11:23 UTC
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

2.7.4

### Moonlight Lib Version

2.13.38

### Issue with mods

it might be quark, I get this error in the crash report
Suppressed: java.lang.NoSuchMethodError: 'net.minecraft.world.item.Item org.violetmoon.quark.content.building.block.VariantChestBlock.asItem()'

### Issue Detail

I try to load the game, it fails. downgrading to the last version fixes this problem

### OPTIONAL: Latest.log | Crash-report Attachment

https://mclo.gs/8KTedre

### OPTIONAL: To Produce

1) load game
2) crash

**Comment by Xelbayria** [comment] 2024-12-16 19:57
alright, i'm checking

### UPDATE: 
Found the cause. 

**FYI**: 
@BurningSulphur 
There is no changes in **Quark Module** between v2.7.3 and v2.7.4.  <strike>You need to update **Moonlight Lib** to v2.13.39.</strike>

EDIT: I ran a test on my side and can reproduce the crash. 

EDIT 2:
Just realized this now:  You don't need to update Moonlight lib yet. the latest moonlight Lib is only required by v2.7.4

**Comment by Xelbayria** [comment] 2024-12-16 20:47
## FIXED in v2.7.5

---

Found the cause.

**Closed as completed** 2024-12-16 20:49 UTC
Labels: bug, 1.20.1-FORGE

**Comment by Krimatoria** [comment] 2024-12-17 12:45
> ## FIXED in v2.7.5
> Found the cause.

But 2.7.5 is not there yet?

**Comment by drakray** [comment] 2024-12-17 17:52
I too would like to know if there's an ETA for 2.7.5, at first I thought it was Curseforge taking it's sweet time to approve, but I don't think so?

**Comment by brisingraerowing** [comment] 2024-12-17 18:24
I've seen CF take 5+ days to approve things on some of the mod-related Discords I'm on. There was one instance where one version got approved *after* the two releases made after it was uploaded (IIRC it was like 10 days after the initial upload)

CF is just weird with approving things sometimes.

**Comment by drakray** [comment] 2024-12-17 18:28
> I've seen CF take 5+ days to approve things on some of the mod-related Discords I'm on. There was one instance where one version got approved _after_ the two releases made after it was uploaded (IIRC it was like 10 days after the initial upload)
> 
> CF is just weird with approving things sometimes.

urgh, I'll just roll back to 2.7.3 for the time being then XD, thanks for the info

**Comment by Xelbayria** [comment] 2024-12-17 20:00
> > ## FIXED in v2.7.5
> > Found the cause.
> 
> But 2.7.5 is not there yet?

There is 1 more bug I need to fix and then all done. Good idea to roll back to v2.7.3

and also roll back Moonlight Lib to v2.13.37 If you are using EC v2.7.3, you won't have any problem
