### ISSUE TITLE
[🐞]: Creative tab log spam

### ISSUE THREAD

**Issue by Dominus-Sicarum** [MehVahdJukaar/WoodGood#633] opened 2024-10-08 23:54 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.82

### Moonlight Lib Version

2.13.3

### Issue with mods

Just the everycompat, I think.

Tested with only following mods to see if the spam happens:
moonlight lib
everycompat
twilight forest
macaw's bridges
storage drawers

### Issue Detail

Insane log spam with the following line:
[Render thread/ERROR] [Every Compat/]: Creative tab cant be null.

There are tens of thousands of those messages per gameplay session (~2 hours) on my main instance of minecraft, and still hundreds on the test instance with minimum mods installed.

### OPTIONAL: To Produce

1. Install a few mods that every compat supports.
2. Create new world.
3. Open creative inventory.
4. Log spam gets exponentially worse with more mods installed.

**Comment by Xelbayria** [comment] 2024-10-09 01:14
i'll check 

ok, The Twilight Forest is the culprit.

**Comment by Xelbayria** [comment] 2024-10-09 01:46
Fixed in v2.6.83. Thanks for the report.

**Closed as completed** 2024-10-09 01:46 UTC
Labels: bug, status: done, 1.20.1-FORGE, 1.20.1-FABRIC

**Comment by Dominus-Sicarum** [comment] 2024-10-12 08:07
@Xelbayria found 2 more mods that cause the same log spam:

[Absent by Design](https://www.curseforge.com/minecraft/mc-mods/absent-by-design)
[More Chest Variants](https://www.curseforge.com/minecraft/mc-mods/more-chest-variants-lieonlion)

**Comment by Xelbayria** [comment] 2024-10-12 08:52
👍🏻  Thanks for the reports. Keep it coming!

**Comment by brisingraerowing** [comment] 2024-10-12 14:22
I'm getting spam referencing Villagers Plus flower tubs (which are internally called `[wood]_horticulturist_table`).

**Comment by Xelbayria** [comment] 2024-10-12 18:06
that make 3 mods.  keep it coming.

**Comment by Xelbayria** [comment] 2024-10-12 21:35
Fixed in v2.6.84
- Absent By Design
- More Chest Variants (LieOnLion)
- Villagers Plus
