### ISSUE TITLE
[Bug] Some Born In Chaos items missing textures

### ISSUE THREAD

**Issue by LolJohn11** [MehVahdJukaar/WoodGood#133] opened 2023-01-25 16:10 UTC
Some wooden modded items generated by EveryCompat using Scorched wood from the [Born in Chaos](https://www.curseforge.com/minecraft/mc-mods/born-in-chaos) mod have partially missing textures as pictured in the screenshot below.

![2023-01-25_17 04 41](https://user-images.githubusercontent.com/49366383/214614372-44ece97b-766a-42e9-9e10-848daef1abf6.png)
_Left to right: scorched wired fence (from Macaw's Fences), scorched bridge support (from Macaw's Bridges), hollow scorched log (from Quark), and scorched log (from Born in Chaos)_

**Comment by Xelbayria** [comment] 2023-10-15 03:32
Is this issue resolved in the latest version? if yes, then please close this issue,

**Comment by LolJohn11** [comment] 2023-10-17 17:18
The issue still persists in the latest version of Every Compat (1.19.2-2.5.10).

**Comment by Xelbayria** [comment] 2023-10-17 18:18
EC has an issue with **Born In Chao** & **Macaw's** & **Quark**, correct? I'll check to find out what's going on. 

- scorched wired fence (Macaw's Fences)
- scorched bridge support (Macaw's Bridges)
- hollow scorched log (Quark) 
- scorched log (Born in Chaos)

Make sure you also update Moonlight Lib to the latest version (so we can rule out Moonlight Lib and EC latest version)

EDIT: Which Wood Type is it

**Comment by LolJohn11** [comment] 2023-10-18 07:47
Just retested on a separate instance with only the relevant mods enabled.
The issue persists on the latest version of all the mods involved:
- Moonlight Library 2.2.46
- Every Compat 2.5.10
- Born in Chaos 1.7
- Quark 3.4-416
- Macaw's Fences 1.0.7
- Macaw's Bridges 2.1.1

The full names of the affected blocks are:
- everycomp:q/born_in_chaos_v1/hollow_scorched_log
- everycomp:mcb/born_in_chaos_v1/scorched_bridge_pier
- everycomp:mcf/born_in_chaos_v1/scorched_wired_fence

The scorched log block in the initial post was put there just for illustration purposes of what the actual texture should look like. That block itself has no issues.

**Comment by Xelbayria** [comment] 2023-10-18 07:57
What an excellent information. With that, I can find out what's going on

**Comment by Xelbayria** [comment] 2023-10-22 08:08
## Details

I checked in `hollow_scorched_log.json` via _model folder_. I also checked **Born In Chaos**'s mod to find the texture. it turned out that `born_in_chaos_v1:block/scorched_log_top` doesn't exist. This is the cause. 

the correct path is supposed to be either `born_in_chaos_v1:blocks/obtes` or `born_in_chaos_v1:blocks/brievnovierknh1`
☝️ are both log_top, I have no clue which one is Log or Wood. 
To be honest, I don't know how to fix this because the name for logs is weird. 

**Best solution?** Contact the dev and have him rename the `scorched` wood to have the same format ID using Minecraft's assets as a reference like below: 
- acacia_log_top
- acacia_log

That will fix the problem with `scorched_log_top` as it is expected to be in the assets. 

EDIT:

**Another solution** is to copy the texture from **Born In Chaos** and put it in your own custom resource pack with the correct name and path. This should allow the 3 blocks to have the purple/black texture replaced by the texture from the resource pack. 

This is another way to fix the problem if the author doesn't want to fix the name problem. I haven't tested it to see if it works. 

I changed the label of this issue because the bug is not related to **Every Compat**, it's related to **Born In Chaos**

**Comment by Xelbayria** [comment] 2023-10-27 08:15
@LolJohn11 Have you contacted the dev? Is there any news regarding this issue?

**Comment by LolJohn11** [comment] 2023-10-27 08:23
@Xelbayria Yes, I have contacted the dev. The answer I got was that they don't know if they can fix this on their side using MCreator, but they were going to take a look and try to fix this. So far I haven't gotten any news regarding that, but a new BiC update should be released "in the near future", I'll see if the fix for this issue will be included in that update.

**Comment by Xelbayria** [comment] 2023-10-27 08:37
hmm. isn't it just simply changing the ID of the block? 

> a new BiC update should be released "in the near future", I'll see if the fix for this issue will be included in that update.

Alright, Let me know if they solved the issue or not.

**Comment by LolJohn11** [comment] 2023-11-03 11:27
> **Another solution** is to copy the texture from **Born In Chaos** and put it in your own custom resource pack with the correct name and path. This should allow the 3 blocks to have the purple/black texture replaced by the texture from the resource pack.
> 
> This is another way to fix the problem if the author doesn't want to fix the name problem. I haven't tested it to see if it works.

I've just tried this way of solving it but wasn't successful, unfortunately.
I've grabbed the correct texture from Born in Chaos, renamed it to `scorched_log_top` and put it in my resource pack in the following folder: `assets\born_in_chaos_v1\textures\blocks\`. This did not fix the issue.

**Comment by Xelbayria** [comment] 2023-11-03 21:57
I'll test the solution on my side and let u know if it's work for me or not

**Comment by Xelbayria** [comment] 2023-11-10 05:15
@LolJohn11 I got it working. I made a few mistakes in what I said in my previous post about how to create the assets. 
`blocks` should be `block` 
![fixed-born-in-chaos](https://github.com/MehVahdJukaar/WoodGood/assets/12866666/75aa5c04-0c47-4fed-a284-5382d0073e09)

I was busy and ended up forgetting about this. sorry about this. I hope this fixes your issue. Let me know if you need the resource pack

the correct path for texture is 
```
fixed-born-in-born.zip
    - pack.mcmeta
    -> assets
        -> born_in_chaos_v1
            -> textures
                 -> block
                     - scorched_log_top.png
```

**Closed as completed** 2023-11-10 05:16 UTC
Labels: status: recalcitrant, status: done, not-related, 1.19.2-FORGE

**Comment by LolJohn11** [comment] 2023-11-10 08:18
@Xelbayria yes, this fixes the issue, thanks!
