### ISSUE TITLE
[🐞]: Crash on boot; java.lang.UnsupportedOperationException: Base block cant be null

### ISSUE THREAD

**Issue by MaxWasUnavailable** [MehVahdJukaar/WoodGood#489] opened 2024-04-10 20:47 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.49.jar

### Moonlight Lib Version

moonlight-1.20-2.11.11-forge.jar

### Issue with mods

Unknown whether it's a hard incompatibility. The stacktrace changes depending on mods removed, but always points at EveryCompat.

This has only started happening since a recent update (one in the past 2 weeks - we update our modpack on a bi-weekly basis).

### Issue Detail

Crashes on boot. Seems potentially related to memory usage, but hard to pin down.

Crash report mentions `java.lang.UnsupportedOperationException: Base block cant be null`

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-04-10_21.37.34-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14937564/crash-2024-04-10_21.37.34-client.txt)

**Comment by Xelbayria** [comment] 2024-04-11 10:20
Can you disable **Create** and check if no crash happened.

**Comment by MaxWasUnavailable** [comment] 2024-04-11 20:11
Still crashes, according to the users who are having this issue.

Seems to be related to https://github.com/MehVahdJukaar/WoodGood/issues/473

**Comment by Xelbayria** [comment] 2024-04-11 20:36
Yeah, it's currently under investigation. The reporter via that link is trying to find out which mod is the culprit. 

and Have you tried without **Create**? I've looked at the crash report. it's pointing at **Create** which is strange. I thought it may be related to **Quark** via the link above in your comment

**Comment by MaxWasUnavailable** [comment] 2024-04-20 22:09
~~Hey hi, @Xelbayria, this seems to potentially be happening whenever a disabled mod file is in the mods folder. Is your mod going through all jars in the mods folder, regardless of them being loaded by forge?~~

Sorry, disregard this. Wasn't related after all.

Some of our users are getting this error purely at random at this point. Sometimes the game boots fine, other times it crashes with this (updated) error.

**Comment by Xelbayria** [comment] 2024-04-21 02:25
> Some of our users are getting this error purely at random at this point. Sometimes the game boots fine, other times it crashes with this (updated) error.

yea. The bug is quite annoying because I can't find the cause. The investigation is still ongoing.

**Comment by MaxWasUnavailable** [comment] 2024-04-22 16:36
> > Some of our users are getting this error purely at random at this point. Sometimes the game boots fine, other times it crashes with this (updated) error.
> 
> yea. The bug is quite annoying because I can't find the cause. The investigation is still ongoing.

Seems like it might have something to do with threaded loading of stuff? Slower/less powerful PCs seem to have the error more consistently, while users with beefy PCs aren't having the issue at all.

Might imply those slower PCs aren't finished loading / patching things when forge expects it to be done?

**Comment by Xelbayria** [comment] 2024-04-22 16:49
I see. At first, I thought the RAM allocation wasn't enough. The "out of memory" or "not enough memory" can lead to a crash.  Either one of these:
- potato PCs may not have enough RAMs to handle the mod pack with Every Comp. 
- The Core/Threads of the CPU may have to do with why Minecraft crashed. 
- There is also a memory leak, too. 

It's hard to pinpoint the real cause

**Comment by MaxWasUnavailable** [comment] 2024-04-22 17:47
> I see. At first, I thought the RAM allocation wasn't enough. The "out of memory" or "not enough memory" can lead to a crash. Either one of these:
> 
>     * potato PCs may not have enough RAMs to handle the mod pack with Every Comp.
> 
>     * The Core/Threads of the CPU may have to do with why Minecraft crashed.
> 
>     * There is also a memory leak, too.
> 
> 
> It's hard to pinpoint the real cause

It seems unrelated to allocated RAM. We've tested this relatively extensively. Unless the memory leak is not deterministic / grows over time rather than over operations (and hence would cause more memory usage for slower PCs), and also a *significant* leak (as in, multiple GB more usage over time, since I can boot our pack with 10GB of RAM, while people who are having the problem can't get it to boot with 12+ GB allocated).

**Comment by Xelbayria** [comment] 2024-06-04 02:05
Are u able to find the culprit regarding this issue?

**Comment by MaxWasUnavailable** [comment] 2024-06-05 07:51
Nope, sorry. I posted all my findings in https://github.com/MehVahdJukaar/WoodGood/issues/473 (including the comments you marked as off-topic). Version 39 was the last stable version for us.

**Comment by Xelbayria** [comment] 2024-06-05 08:58
Oh ok. I'll be closing this and the discussion will keep going on in **Issue-473**. Apparently, it seem to be related to the potato computer and high-end PC. Potato PC have problem with launching Minecraft while High-end PC don't.

**Closed as not planned by Xelbayria** 2024-06-05 08:58 UTC
Labels: bug, 1.20.1-FORGE
