### ISSUE TITLE
[Feature] Ars Nouveau Support

### ISSUE THREAD

**Issue by brnbrd** [MehVahdJukaar/WoodGood#43] opened 2022-09-01 17:46 UTC
Every Compat should at least generate blocks for one of Ars Nouveau's Archwood Logs (all planks are the same). In Discord we discussed and decided the blue one would be best.

**Comment by Xelbayria** [comment] 2023-10-15 00:38
is this issue solved? If yes, then please close this

**Comment by ali-afk** [comment] 2023-10-24 14:33
Can't more wood types be added?

**Comment by Xelbayria** [comment] 2023-10-24 19:30
Does it have other wood types? 

Every Compat (EC) should be able to detect that and combine it with other furniture from mods. That's assuming the ID format for woods are `<name>:<type>_log`  or `<name>:<type>_wood`

where: 
- \<name>: biomesoplenty, twilightforest
- \<type>: oak, birch, redwood, others.

**Comment by Xelbayria** [comment] 2024-01-31 08:04
I'll be closing this since I haven't heard from you for a while. 

a bit more details. EC can detect the wood/log by sound "bass". so The woods must have the "bass" sound. if EC cannot detect them, that means the problem is on Mod's side, not EC. You'll have to let Dev know so the mod can be properly updated.

**Closed by Xelbayria** 2024-01-31 08:04 UTC
Labels: module
