### ISSUE TITLE
[🐞]: Regions Unexplored/Quark Brimwood Chest

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#356] opened 2023-12-04 06:54 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycompat-1.19.2-2.5.14

### Moonlight Lib Version

1.19.2-2.3.5

### Issue with mods

Regions Unexplored
Quark

### Issue Detail

The chest has missing texture
![image](https://github.com/MehVahdJukaar/WoodGood/assets/150559423/5a434640-4d4e-4f84-aaa7-e9d40b0f4b72)

**Comment by Xelbayria** [comment] 2023-12-04 16:53
@MehVahdJukaar 

I was able to find the cause of this problem: 
`Failed to generate Chest block texture for for Block{everycomp:q/regions_unexplored/brimwood_chest} : java.lang.IllegalStateException: Could not merge images because they had different dimensions`

what's going on?

**Comment by MehVahdJukaar** [comment] 2023-12-04 17:31
Is that texture animated?

**Comment by Xelbayria** [comment] 2023-12-04 18:07
Yes, it is animated. (just checked)

**Comment by Xelbayria** [comment] 2023-12-25 06:18
@OminousDiscovery 
tbh, idk how to fix the problem since the texture is animated.  One solution is to create a non-animated texture for planks/log and put it in your resource pack. that should fix the problem.

**Comment by Krimatoria** [comment] 2024-01-09 00:28
> @OminousDiscovery tbh, idk how to fix the problem since the texture is animated. One solution is to create a non-animated texture for planks/log and put it in your resource pack. that should fix the problem.

Has there been no solution? I noticed a few more blocks with this problem.

**Comment by Xelbayria** [comment] 2024-01-09 01:38
> > @OminousDiscovery tbh, idk how to fix the problem since the texture is animated. One solution is to create a non-animated texture for planks/log and put it in your resource pack. that should fix the problem.
> 
> Has there been no solution? I noticed a few more blocks with this problem.

I mentioned the solution. The problem is the texture from **Region Unexplored** is animated and does not work with how EC uses textures together with other wood types' textures. I'm not sure why the animated texture from **Regions Unexplored** doesn't work with EC. 

Another option is you ask the devs to fix the texture so it will work with EC. I also noticed some blocks with animation are working fine with EC like **XercaMod**'s carved blocks. 2 of them have animated textures. 

EDIT: 
there is nothing wrong with **Every Compat**'s texture system. the problem is on **Region Unexplored** side.

**Comment by Xelbayria** [comment] 2024-02-14 01:28
The brimwood texture problem is fixed in 1.20.1, it will be in 
- v2.6.33 of **EveryCompat** 
- v2.9.14 of **Moonlight Lib**

the same fix will be applied to 1.19.2, too.

**Comment by Krimatoria** [comment] 2024-02-14 19:02
> Проблема с текстурами коры исправлена ​​в версии 1.20.1, она будет в
> 
> * v2.6.33 **EveryCompat**
> * v2.9.14 **Moonlight Lib**
> 
> то же исправление будет применено и к версии 1.19.2.

Eeeee)

**Closed as completed** 2024-02-16 00:41 UTC
Labels: bug, status: done, 1.19.2-FORGE
