### ISSUE TITLE
Corail Woodcutter Compat

### ISSUE THREAD

**Issue by breadguyyy** [MehVahdJukaar/WoodGood#15] opened 2022-06-17 17:42 UTC
Would love to see woodcutter recipes generated for this mod. Considering what the two mods do, they would perfectly compliment each other

**Comment by Xelbayria** [comment] 2023-10-15 00:22
is this issue resolved? If yes, then please close this

if not, then please fill out the following: 
- Loader: (Forge or Fabric)
- Which mod to enhance or add: "Corail Woodcutter"??? correct? 

---

**DETAILS**
- Minecraft Version: 1.18.2

**Comment by breadguyyy** [comment] 2023-10-17 16:35
this has not been solved yet. I'm using Forge and the mod is Corail Woodcutter. I'm looking for auto generated variants for the woodcutters and for all other recipes generated by this mod to be automatically added to the woodcutter. pic attached for reference.
![image](https://github.com/MehVahdJukaar/WoodGood/assets/21149431/2c230f87-d0b9-408c-92ad-76f2feafb1f5)

**Comment by Xelbayria** [comment] 2023-10-17 18:24
Ok, can you please fill out the information using my post as a reference before your post? 

The issue is that EC did not add the block (TABLE) from Corail Woodcutter to the recipe system of Sawmill/woodcutter. correct

**Comment by breadguyyy** [comment] 2023-10-17 19:14
Loader: Forge
Which mod to enhance or add: Corail Woodcutter
Minecraft Version: 1.18.2, 1.19.2, 1.20.1

Suggested functionality: 
 - Add a Sawmill/Woodcutter block for every wood type
 - Automatically add all everycompat generated blocks and items to the woodcutter (ie. put aspen logs/planks into the woodcutter and have aspen cabinets, tables, chairs, etc. show up in the crafting menu)

**Comment by Xelbayria** [comment] 2023-10-17 19:22
Alright, The furniture (cabinet, tables, chair), are they also from **Corail Woodcutter**? 

if yes, then I can use both points in your post to add support for **Corail Woodcutter** via EC

**Comment by breadguyyy** [comment] 2023-10-17 19:24
no, the only block corail woodcutter adds is the woodcutter/sawmill. the other blocks I mentioned are examples of blocks from other mods supported by everycompat. the woodcutter acts as a stonecutter does but for wood, so the idea is that since everycompat adds loads of wood blocks and items it would generate them into the woodcutter automatically.

**Comment by breadguyyy** [comment] 2023-10-17 19:25
whoops didn't mean to hit close lol

**Comment by Xelbayria** [comment] 2023-10-17 20:50
> no, the only block corail woodcutter adds is the woodcutter/sawmill. the other blocks I mentioned are examples of blocks from other mods supported by everycompat. the woodcutter acts as a stonecutter does but for wood, so the idea is that since everycompat adds loads of wood blocks and items it would generate them into the woodcutter automatically.

Ah, I was thinking about what type of block did "cutter block" Minecraft has. it was a "stonecutter". I understand now. I'll check out the system of **Corail Woodcutter** to see how it works.

**Comment by Xelbayria** [comment] 2023-10-18 04:22
Already mentioned in [MOD SUPPORT SUGGESTION](https://github.com/MehVahdJukaar/WoodGood/issues/77)

**Comment by Xelbayria** [comment] 2024-11-10 10:55
## SUPPORTED IN 1.18.2 v1.6.8

---

#### NOTE:

it won't be supported in 1.19.2 and onward. There is this: [sawmill mod](https://www.curseforge.com/minecraft/mc-mods/sawmill) that does the same thing using Moonlight lib which will find... well blocks and add them in sawmill.

**Closed** 2024-11-10 10:55 UTC
Labels: duplicate, enhancement, Module
