### ISSUE TITLE
9 megabytes of everycomp errors in log 

### ISSUE THREAD

**Issue by inikishev** [MehVahdJukaar/WoodGood#239] opened 2023-08-26 11:46 UTC
https://gist.github.com/stunlocked1/84cfbe1d29b4ec2c51d74d1bd4a534ab

**Comment by MehVahdJukaar** [comment] 2023-08-26 12:07
Seems like chipped moved their textures so all their EC blocks can't find them

**Comment by Xelbayria** [comment] 2023-10-13 03:58
Does this issue still persist, if no, then please close this issue

**Comment by inikishev** [comment] 2023-10-13 06:23
> Does this issue still persist, if no, then please close this issue

it does https://gist.github.com/stunlocked1/c01e110137157f70260cd2bdfc1f4066

**Comment by Xelbayria** [comment] 2023-10-13 06:51
Can you fill the information:
- EveryCompat version: ??????

---

Minecraft Version: **1.20.1**
Loader: **Fabric**
Moonlight Lib: **2.8.50**
Which Mods does EC have an issue with:
- **Chipped v3.0.1**

### Extra Information: 
**File Not Found:**
- `chipped:block/oak_planks/ctm/oak_planks_panel_ctm` 
- `chipped:block/oak_planks/ctm/cornered_oak_planks_ctm` 
- `chipped:block/oak_planks/ctm/enclosed_oak_planks_ctm`
 
- `chipped:block/glass/ctm/oak_bared_glass_ctm` 
- `chipped:block/glass/ctm/oak_bordered_glass_ctm` 
- `chipped:block/glass/ctm/oak_horizontal_lined_glass_ctm`
- `chipped:block/glass/ctm/oak_large_diamond_glass_ctm`
- `chipped:block/glass/ctm/oak_line_bared_glass_ctm`
- `chipped:block/glass/ctm/oak_ornate_bared_glass_ctm`
- `chipped:block/glass/ctm/oak_woven_glass_ctm`
- `chipped:block/glass/ctm/square_oak_glass_ctm`
- `chipped:block/glass/ctm/oak_bared_glass_ctm`
- `chipped:block/glass/ctm/square_oak_glass_ctm`
- `chipped:block/glass/ctm/oak_woven_glass_ctm`
- `chipped:block/glass/ctm/oak_ornate_bared_glass_ctm`
- `chipped:block/glass/ctm/oak_line_bared_glass_ctm`
- `chipped:block/glass/ctm/oak_large_diamond_glass_ctm`
- `chipped:block/glass/ctm/oak_horizontal_lined_glass_ctm`
- `chipped:block/glass/ctm/oak_bordered_glass_ctm`

**Failed To Generate texture:**
- `Failed to generate texture everycomp:block/ch/blockus/legacy_planks/brick_bond_oak_planks`
- `Failed to generate texture everycomp:block/ch/blockus/legacy_planks/polished_oak_planks`

@MehVahdJukaar  look at this ☝️  that's the same issue with Terraqeuous. We'll need to find out what's the cause to _failed to generate texture_

**Comment by inikishev** [comment] 2023-10-14 06:19
> * EveryCompat version: ??????

its 1.20-2.6.7

**Comment by MehVahdJukaar** [comment] 2023-10-14 22:03
Maybe nearer versions changed the locations of those textures and ec still looks in the old place or they are straight out wrong. Does ctm work for chipped EC stuff?

**Comment by Xelbayria** [comment] 2023-10-14 22:33
> Maybe nearer versions changed the locations of those textures and ec still looks in the old place or they are straight out wrong. Does ctm work for chipped EC stuff?

I am going to investigate the ctm stuff.

**Comment by Xelbayria** [comment] 2023-10-15 08:51
hmm. I checked the Forge version, same issue. Something's wrong with the module

EDIT: 
ok this makes no sense. I checked the path to `chipped:block/oak_planks/ctm/...` and it is correct. yet it cannot find the files?

**Comment by Xelbayria** [comment] 2023-10-15 20:20
@stunlocked1 

what's the version of Moonlight?

**Comment by Xelbayria** [comment] 2023-10-15 22:15
## Details: 
Found the cause. The CTM textures have changed. and it's a major change.  The github's source code is outdated. 
An alternative method is to use 7zip to look in the official mod, **chipped v3.0.1** and check the path of these CTM textures. 

---

**The cause for** `failed to generate texture` **is unknown.** 

EDIT: 
The reason for these "failed to generate textures" could be due to the number of colors being less than 7 colors which is not enough for the system to create a new texture. This is not confirmed. Something to keep in mind. 

On another note, it is confirmed on **Terraqueous** mod where 3 types of Clouds' textures have 5 numbers of colours and it leads to "Failed to generate textures".

**Comment by Xelbayria** [comment] 2023-10-20 21:49
The issue regarding the texturing with _CTM_ stuff. The fixes will be included in v2.6.9. 

EDIT: 
1.20.1 is finished & running test

EDIT: 
ran into an issue regarding 3 blocks with CTM texture. Will take some time to resolve.

EDIT:
Finished and it will be in the next version, v2.6.9

**Closed as completed** 2024-02-09 01:17 UTC
Labels: bug, 1.20.1-FORGE, status: cause found
