### ISSUE TITLE
[🐞]:  Missing Planks from Regions Unexplored

### ISSUE THREAD

**Issue by LunarDev-git** [MehVahdJukaar/WoodGood#511] opened 2024-05-11 13:36 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20.2.6.55

### Moonlight Lib Version

1.20.2.11.17

### Issue with mods

RegionsUnexploredForge-0.5.5+1.20.1.jar

### Issue Detail

Sometimes upon boot, planks from Regions Unexplored won't load. However it is random. Yesterday I was able to reproduce the error nearly everytime upon boot to the point I managed to ascertain that it was Everycomp causing the issue as when I disabled it and booted back into the world recipe was there, enabled it and it wasn't

(due to nature of the bug happening randomly, tried this multiple times and still found everycomp was at fault)

However, today when testing it, I'm not able to reproduce it at all and everything is the same. It happens so randomly, it's so annoying to figure out the cause. The only latest log I have is when I had it happen with a BUNCH of mods so I won't post that one.

Continuation of https://github.com/MehVahdJukaar/sawmill/issues/21

Forge Version: 47.2.32

### OPTIONAL: To Produce

It is random but how I did it was just

1 ) Start new world (singleplayer or server)
2 ) Bug is present when trying to craft planks from RU

**Comment by Xelbayria** [comment] 2024-05-12 06:47
This will need an investigation to find the cause of the bug. This won't be fixed, not until the cause is found. Try and see if you can run a simple test with: 
- EveryComp (EC)
- Regions Unexplored (RU)
- Moonlight Lib
- Furniture Mod of your choice. 

check whether it produces the bug or not. If the bug was never produced, then a mod in the mod pack is somehow causing the problem. Of course, you may have to launch Minecraft a few times to get the "bug" at random time.

**Comment by LunarDev-git** [comment] 2024-05-14 16:47
OKAY! SO. I wanted to whittle it down to as little mods as possible. I think you'll find it's Builder's Additions causing it,. which makes kinda sense because of what's left behind in the recipes after the bug has happened. 

It could be a clash between a lot of these, I will keep trying to lowering the mods to really refine the mod causing the issue but it took me this long to get to this point. just wanted to update where I'm at.

Screenshot of the mods currently in the pack with the bug happening.


<details>

<summary>Images</summary>

![image](https://github.com/MehVahdJukaar/WoodGood/assets/105180230/cb3d88db-d151-4b16-8422-522a66d3efee)

</details>

latest.log
https://bytebin.lucko.me/MN5m2Cgmab

**Comment by LunarDev-git** [comment] 2024-05-14 17:50
:)

<details>

<summary>Images</summary>

![image](https://github.com/MehVahdJukaar/WoodGood/assets/105180230/d36ac80d-7e6d-4ce2-93ba-1a5e469269f6)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/105180230/98d630bf-c968-4101-a408-38ce73214af4)

</details>

**Comment by Xelbayria** [comment] 2024-05-14 20:05
I'll run a test with these mods and see if I can replicate the issue on my side.

**Comment by LunarDev-git** [comment] 2024-05-14 20:13
Yep! Just a heads up, what I do to make it easier

Use server pack creator to make a quick server

1 - Launch world see if it works 
2 - give myself log
3 - if issue isn't present delete world and go back to step one

Usually, i've had it happen in under 10 times but sometimes more if i'm unlucky

**Comment by Xelbayria** [comment] 2024-05-14 20:17
By recipes being missed or skipped. 

do you mean the recipe is not showing up below? 
<details>

<summary>Images</summary>

![recipe_issue_511](https://github.com/MehVahdJukaar/WoodGood/assets/12866666/5c78dcef-a469-4015-9c82-be437542f305)

</details>
if yes, then try using JEI or REI to see if all of the recipes show up

**Comment by LunarDev-git** [comment] 2024-05-14 20:18
So, when I give myself a log, it will automatically show the plank recipe, the plank recipe will be red/uncraftable. the bug is still visible with JEI thought but i tried the least mods possible


i give myself a mauve_log because that's the log I originally found the bug with

**Comment by Xelbayria** [comment] 2024-05-14 20:24
Wait. The bug occurred in the Server world, not the Client world (SP = Singleplayer) ?

If yes, then I'll need the latest.log with the bug occurred

**Comment by LunarDev-git** [comment] 2024-05-14 20:30
My tests here are on a Server world due to it being quicker to replicate but I have had reports of it in singleplayer from modpack users


Here is the JEI bug screenshot
<details>

<summary>GIF</summary>

![firefox_D4ZzYscPiM](https://github.com/MehVahdJukaar/WoodGood/assets/105180230/11b9fc51-e595-4a53-9c13-5b525150a0e9)

</details>
here is the latest log from the server

https://bytebin.lucko.me/gZqdGjEn4D

**Comment by LunarDev-git** [comment] 2024-05-14 20:30
Just checked other planks, bug extends to every RU wood

**Comment by Xelbayria** [comment] 2024-05-14 20:35
oh, that's what's going on. Let me check on my side. 

### UPDATE: 
The problem exists. I'll be looking into this and get it fixed. it seems the problem is from Builders Craft & Addition (via EveryComp)

**Comment by LunarDev-git** [comment] 2024-05-14 20:40
Oh thank god! I'm not going crazy 

However, it seems harder to replicate on singleplayer

All these and no bugs T-T

<details>

<summary>Image</summary>

![image](https://github.com/MehVahdJukaar/WoodGood/assets/105180230/cddc4098-a933-4008-9798-a06cd0972578)
</details>

**Comment by Xelbayria** [comment] 2024-05-14 21:41
**UPDATE:** 
I found the problem. I don't know why. I think the second recipe that EveryComp is trying to replicate and replace with the WoodType somehow is overriding the (from log to plank) recipe.  I believe the reason is "result" for both recipes from **Region Unexplored (RU)** & Minecraft are the same. 

I checked Biomes O' Plenty (BOP). There is no problem. Only **RU** have this bug and it's strange. I tried to use the reverse recipe which is: 2 vertical slabs to craft a plank (it doesn't work in BOP) because the plank recipe wasn't overwritten.

the fact you discover this bug is a great thing

**Comment by LunarDev-git** [comment] 2024-05-14 22:06
It's been plaguing my pack for a while! I do have the forge dev of RU up to date on this as I have a ticket in their discord
But thank you for the explanation, I always love hearing how bugs occur and this one was a nightmare

So wait, is it everycomp or builder's additions?

**Comment by Xelbayria** [comment] 2024-05-14 22:21
The problem is actually in **Moonlight Lib**, that's where **EveryComp (EC)** is using to create similar recipes from the original recipes via mod for blocks/items that **EC** have created. The RecipeBuilder system doesn't account for 2 recipes with the same name. 

EDIT: 
I'm not familiar with the whole picture of how recipe stuff works yet. For now, I'll create a quick fix to the problem and upload **EC** later. 


### UPDATE: 

Fixed and will be in the next version.

**Closed as completed** 2024-05-15 04:22 UTC
Labels: bug, status: done, 1.20.1-FORGE, status: cause found
