### ISSUE TITLE
[1.20.1] [fml mod] No Better End woodtype support

### ISSUE THREAD

**Issue by Cixon** [MehVahdJukaar/WoodGood#241] opened 2023-08-26 22:14 UTC
Using Sinytra Connector, FML can easily run fabric mods now. I have Terrestria [fabric mod] installed and their woodtypes are not available to me; same with BetterEnd when using MrCrayfish furniture. However, fabric leaves (hedges) do appear and function great.

### Image of BetterEnd Tenanea Hedge running on Forge:
![Screenshot (52)](https://github.com/MehVahdJukaar/WoodGood/assets/69068153/2f5b5a93-397c-48ae-93ed-d071973726e1)

Sinytra connector will be the next big thing so it's definably viable to get the woodtypes working since it appears the fabric leaves work out of box.

### Sources:
https://legacy.curseforge.com/minecraft/mc-mods/sinytra-connector
https://legacy.curseforge.com/minecraft/mc-mods/forgified-fabric-api

https://legacy.curseforge.com/minecraft/mc-mods/betterend/files/4677967
(and BCLib, exclude Fabric API)

https://legacy.curseforge.com/minecraft/mc-mods/terrestria/files/4710309
https://legacy.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/4602980

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:19
That's weird, as far as I knew fabric mods were loaded pretty much same time as others but the static nature of their registration would make their blocks being added immediately, through connector hacks. What's werider is that leaves types work and others do not. Of those are indeed from the same mod it makes even less sense

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:20
Can you test with other mods that add wood, heck even terrestria on fabric version. Only explanation is that wood detection is somehow failing for those woods

**Comment by Cixon** [comment] 2023-08-26 22:25
> Can you test with other mods that add wood, heck even terrestria on fabric version. Only explanation is that wood detection is somehow failing for those woods

The Terrestria mod doesn’t show any signs of their wood type working with Every Compat, I even tried Cinderscapes. I will say, there’s definitely forge wood type detection as you can see in the screenshot, that mod is gardens of the dead

https://legacy.curseforge.com/minecraft/mc-mods/gardens-of-the-dead

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:27
So I know for almost certain that terrstria woods and leaves register at same time. With fabric unfortunately there isn't really a dedicated step where that can happen tho but even fabric mod version works under that assumption and these woods do work there so I have absolutely no idea why the registries wouldn't be filled up when forge registers it's stuff

**Comment by Cixon** [comment] 2023-08-26 22:30
> So I know for almost certain that terrstria woods and leaves register at same time. With fabric unfortunately there isn't really a dedicated step where that can happen tho but even fabric mod version works under that assumption and these woods do work there so I have absolutely no idea why the registries wouldn't be filled up when forge registers it's stuff

It could be a Sinytra error, I’d assume. I would @  Su5eD as that’d be our answer to this discrepancy. I’m no programmer so I couldn’t say for sure but it still begs the question as to why leaves show up and wood don’t…

**Comment by Cixon** [comment] 2023-08-26 22:32
I don’t think it’s open source but here’s github:

https://github.com/Sinytra/ForgifiedFabricAPI
-
https://github.com/Sinytra/Connector

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:33
I can't test these days but incase it doesn't work wood types for a couple more fabric mods (and leaves types are registered) the that would confirm tha wood type detection is somehow getting confused. Very weird as it's mostly I'd based and I checked connector loads fabric registries basically as soon as the game starts, way way before forge even loads mods. Confusing stuff . Can you try with twilight forest fabric?

**Comment by Cixon** [comment] 2023-08-26 22:36
Not available for 1.20.1 fabric

At least on curseforge..maybe there’s a build somewhere

**Comment by Cixon** [comment] 2023-08-26 22:38
I can test Better Nether and find other fabric wood mods though!

**Comment by MehVahdJukaar** [comment] 2023-08-26 22:39
Ah hm just trying to think of some other I know really well and I'm sure work on fabirc only. Biomes o plenty?

**Comment by Cixon** [comment] 2023-08-26 22:58
> Ah hm just trying to think of some other I know really well and I'm sure work on fabirc only. Biomes o plenty?

I could attempt to use the fabric version of everycomp woodgood but this may result in the forge compat not working lol

**Comment by MehVahdJukaar** [comment] 2023-08-26 23:06
Oh lol that would be cursed. Not only that but for how it's made it will not work as it will only see stuff registered by fabric mods

**Comment by Cixon** [comment] 2023-08-27 23:54
> Oh lol that would be cursed. Not only that but for how it's made it will not work as it will only see stuff registered by fabric mods

### Made a discovery.....

Architectury API (forge version) ruins the wood registries for fabric mods.
I spent nearly the whole day diagnosing a bunch of things 1 by 1 and found that there's not anything inherently wrong with WoodGood. Disabling shedaniel's API fixed this bizarre situation with only leaves being supported by WoodGood.

### It's 50/50 - some mods work, some don't, screenshot below shows Regions Unexplored (fabric)

![Screenshot (53)](https://github.com/MehVahdJukaar/WoodGood/assets/69068153/d6ec21e3-185d-4628-a848-7590607d2b9c)


It appears to be a shedaniel issue but again, I'm no programmer so maybe you could made a patch for the API?
One thing I know for sure is, BetterEnd isn't supported for the current WoodGood FML version.

**Comment by Cixon** [comment] 2023-08-28 00:00
**Conclusion:** Some fabric woodtypes work and some need manual support such as BetterEnd and Terrestria.

**Comment by Xelbayria** [comment] 2023-10-13 03:45
hmm isn't this **enhancement** for EveryCompat to work with fabric with Minecraft running Forge? 
If yes, then perhaps, i should change the label to **enhancement** instead of **module**

**Comment by MehVahdJukaar** [comment] 2023-10-14 22:24
Yeah any issue due to connector can be considered theirs

**Comment by An-thracene** [comment] 2023-10-17 05:05
the compat for terrestria doesn't work on 1.20 fabric too, is it an expected situation?

**Comment by MehVahdJukaar** [comment] 2023-10-17 11:23
To be classified as a wood type a block needs to fulfil some characteristic that all wood types have such has having the bass sound type for noteblocks. Do those blocks have that? If not it's not my issue

**Comment by An-thracene** [comment] 2023-10-17 14:45
> To be classified as a wood type a block needs to fulfil some characteristic that all wood types have such has having the bass sound type for noteblocks. Do those blocks have that? If not it's not my issue

Well I tested, and I found that it has a harp sound for noteblocks...I will report it to them

**Comment by gniftygnome** [comment] 2023-10-17 17:46
> To be classified as a wood type a block needs to fulfil some characteristic that all wood types have such has having the bass sound type for noteblocks.

OK but when you say "some" I wonder what the other assumptions are...

Also, we are talking about the planks block specifically, right?

And finally, we use `FabricBlockSettings.copyOf()` and I think this issue may be resolved when the following change is merged to FAPI:  https://github.com/FabricMC/fabric/pull/3373

**Comment by Xelbayria** [comment] 2024-11-11 10:26
**Details:**
- causes of the issues are discovered & reported to Devs of the respective mod 
- an issue caused by Sinytra Connector is not EveryCompat's issue
- Some mods is somehow screwing up the wood registry on Fabric side

That's it. hope the issue are all resolved.

**Closed as completed by Xelbayria** 2024-11-11 10:26 UTC
Labels: enhancement

**Comment by MehVahdJukaar** [comment] 2024-11-11 11:45
that mod has been blacklisted from ec detection system as they do use dynamic registration too which makes it incompatible with EC since due to many internal issues. It was thus decided to backlist to avoid errors
