### ISSUE TITLE
[🐞]: Latest Update Causes Crash on Server When Used with Variant Vanilla Blocks

### ISSUE THREAD

**Issue by Helinos** [MehVahdJukaar/WoodGood#578] opened 2024-08-05 02:08 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.70

### Moonlight Lib Version

moonlight-1.20-2.12.9-fabric

### Issue with mods

- Variant Vanilla Blocks 1.3.8 
When replaced with twigs there was no crash

- Any mod that adds wood 
I Tried Nature's Spirit and Cinderscapes separately to ensure it wasn't either one that was the problem.

### Issue Detail

Crash when trying to start a server. This does not happen in single player.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/16489814/latest.log)
Crash was not logged to the crash-report folder

**Comment by Xelbayria** [comment] 2024-08-05 04:44
I'll check and this will be fixed in v2.6.71

**Comment by ImBehinYa** [comment] 2024-08-06 07:32
can confrim same issue

**Comment by Xelbayria** [comment] 2024-08-06 07:41
I can reproduce the issue on my side. idk why. I'm talking to MehVahdJukaar about this.

**Comment by Xelbayria** [comment] 2024-08-09 01:59
good news: I found the cause of the problem (it's complicated) & bad news: it will take times to fix the problem.

**Comment by mlus-asuka** [comment] 2024-08-09 15:48
Same issue.I guess you tried to use this method then failed register items
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 59 more

**Comment by Xelbayria** [comment] 2024-08-09 18:43
> Same issue.I guess you tried to use this method then failed register items Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] ... 59 more

Thank you! You just helped me find one more class that I need to add the annotation. 
Annotation is to tell the SERVER to not use class (its' only used on CLIENT) so it can run properly. 

however, the problem is the annotation is not being applied to `BlockEntityRenderer`, SERVER is still trying to find that class and leads to a crash

**Comment by mlus-asuka** [comment] 2024-08-09 18:56
> > Same issue.I guess you tried to use this method then failed register items Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] ... 59 more
> 
> Thank you! You just helped me find one more class that I need to add the annotation. Annotation is to tell the SERVER to not use class (its' only used on CLIENT) so it can run properly.
> 
> however, the problem is the annotation is not being applied to `BlockEntityRenderer`, SERVER is still trying to find that class and leads to a crash

that's won't work if only use annotation. try run it in FMLClientStartUp event

**Comment by Xelbayria** [comment] 2024-08-09 20:36
Fixed in v2.6.71

the problem is much more weirder than I thought.

**Closed as completed by Xelbayria** 2024-08-09 20:36 UTC
Labels: bug, 1.20.1-FABRIC, server
