### ISSUE TITLE
[🐞]: Mipmapping issue

### ISSUE THREAD

**Issue by andrwcrr** [MehVahdJukaar/WoodGood#654] opened 2024-10-28 06:01 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycompat-1.20-2.6.87

### Moonlight Lib Version

moonlight-1.202.13.17

### Issue with mods

N/A

### Issue Detail

From version 1.20-2.6.84 onwards of Every Compat there is an issue which looks like my mipmap settings are forced off or lowered, seen most prominently in water like in the attached image.
![{69EBD05D-A029-4095-92B4-1495F885353F}](https://github.com/user-attachments/assets/50a13d66-a82b-4510-b10a-7e2e515994f0)

**Comment by Xelbayria** [comment] 2024-10-28 06:27
I need the latest.log

**Comment by andrwcrr** [comment] 2024-10-28 07:01
[latest.log](https://github.com/user-attachments/files/17538553/latest.log)

**Comment by Xelbayria** [comment] 2024-10-28 07:25
i found the cause. The cause is Building But Better mod. I did not notice until now. 

One of the textures in Building But Better is actually 18x16. The block is `oak_lantern`.

EveryCompat has a mask texture for that block which is also 18x16. That should be what caused the mipmapping to limited to a lower level or off.

**Comment by MehVahdJukaar** [comment] 2024-10-28 07:25
Was about to say that

**Comment by Xelbayria** [comment] 2024-10-28 07:33
There is nothing I can do about the issue. The mask texture has to be exactly same as the original texture for oak_lantern. The solution is up to the dev of **Building But Better**. The solution are mentioned in the link above

**Comment by andrwcrr** [comment] 2024-10-28 07:42
Understood, thanks for raising the issue to the Building But Better dev.

**Comment by Xelbayria** [comment] 2024-11-05 04:27
Looks like the Dev is not replying to the issue I created. I am going to remove the mask_texture for now. It's also removed in 1.21. 

I'll be closing this as it's resolved. There is nothing I can do about the size of texture blc it's an issue on mod's side. 

### REMOVED the oak_lantern_m in v2.6.88

Reason: the texture is 18x16, should be 16x16 or 32x32.

**Closed as completed** 2024-11-09 20:46 UTC
Labels: bug, status: recalcitrant, 1.20.1-FORGE, 1.20.1-FABRIC
