### ISSUE TITLE
[🐞]: Missing textures for blocks from Chipped with BOP

### ISSUE THREAD

**Issue by AltheaGrimm** [MehVahdJukaar/WoodGood#358] opened 2023-12-07 14:40 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.18.jar

### Moonlight Lib Version

moonlight-1.20-2.8.67-forge.jar

### Issue with mods

Biome's o Plenty 
Chipped

### Issue Detail

Biome's o Plenty wood types have a lot of missing Chipped textures. I have reproduced it with mahogany, fir and jaracanda at this point in my game.
<img width="356" alt="image" src="https://github.com/MehVahdJukaar/WoodGood/assets/153198176/a3e617ed-8576-43f8-bcf9-501be438d793">

### OPTIONAL: To Produce

1. Place biome's o plenty wood planks type in the chipped carpenter's workbench
2. You should see more missing textures thank working ones for at least mahogany, jaracanda and fir wood planks

**Comment by Xelbayria** [comment] 2023-12-07 22:45
I cannot reproduce this issue. I had no problem. The problem is not the mods or Every Compat, it's on your side. 

EDIT: 
have you isolated your Minecraft game with:
- Moonlight Lib
- Every Compat
- Biomes O' Plenty
- Chipped

If you have no problem, then something else is causing the problem.

**Comment by Xelbayria** [comment] 2023-12-20 02:28
There has been no reply for a while, I'll close this. If you still have a problem, then you can re-open this issue. Make sure you update Both **Every Compat** & **Moonlight** to the latest version.

**Closed as not planned by Xelbayria** 2023-12-20 02:28 UTC
Labels: bug, 1.20.1-FORGE, status: noreply, can't reproduce
