### ISSUE TITLE
[🐞]: When using forge server with EasyAuth on Sinytra Connector - offline players have visual bug

### ISSUE THREAD

**Issue by rymusov** [MehVahdJukaar/WoodGood#596] opened 2024-08-25 16:03 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.72

### Moonlight Lib Version

1.20-2.12.16

### Issue with mods

Quark 4.0 460
BloomingNature 1.0.9
Handcrafted 3.0.6

### Issue Detail

Issue happend when i set server to online-mode: true and tries join with offline account (via EasyAuth) and cause happend random block type
https://drive.google.com/file/d/18FPaYg2neTiCuNOBdfH7fu7ng_nqjqUH/view?usp=sharing - video explain of bug, before this happend same with Create: Factory Must Grow, when i recreate modpack mod by mod, i see issue happend after adding Every Compat

### OPTIONAL: Latest.log | Crash-report Attachment

[latest (13).log](https://github.com/user-attachments/files/16741048/latest.13.log)

### OPTIONAL: To Produce

1) Install Forge server
2) Install to the server EasyAuth, Blooming Nature and Handcrafted
3) Join to server with those mods and try set something from every compat

**Comment by Xelbayria** [comment] 2024-08-25 17:12
weird. Can you exclude **EasyAuth** and see if the issue persist. 

Can you confirm the issue only existing in SERVER world (no issue in SINGLEPLAYER world)?

**Comment by rymusov** [comment] 2024-08-25 19:27
only happend on server with online mod + easyauth, without it everything good, but i ask EasyAuth creater and he doesnt know what that cause
in singleplayer everything good

**Comment by Xelbayria** [comment] 2024-08-25 23:43
I don't know what's the cause, either. You should test on server without EasyAuth. Something is causing the sync to be "desync" between your Client and Server. 

The thumb rule is to ensure that you are using the exact same version of mod on both Client and Server.

**Comment by MehVahdJukaar** [comment] 2024-08-26 02:01
Turn on the debug packet in the configs on server and client. Not that it would solve it but would be interesting to see what that says

**Comment by Xelbayria** [comment] 2024-09-01 20:58
Any progress on this?

**Comment by rymusov** [comment] 2024-09-02 18:37
> I don't know what's the cause, either. You should test on server without EasyAuth. Something is causing the sync to be "desync" between your Client and Server.
> 
> The thumb rule is to ensure that you are using the exact same version of mod on both Client and Server.

Its only happend when installed EasyAuth and online-mode: true, i switched auth mod to SimpleLogin and everything works perfect now, why EasyAuth and EveryCompat cause problems and how - i dont know

**Comment by Xelbayria** [comment] 2024-09-02 19:08
Have you tested without **EveryComp** to check if the issue persists. (with **EasyAuth** installed). If the issue doesn't persists, then you should let the dev of **EasyAuth** know about this issue.

**Comment by rymusov** [comment] 2024-09-02 19:32
I tested without and everything alright, only if online-mode:true + installed EveryCompat + EasyAuth + BloomingNature (For testing). When i try join to server with offline account = blocks from everycompat get messed

**Comment by Xelbayria** [comment] 2024-09-02 20:44
Interesting, You should speak to the dev of **EasyAuth** about this issue.

**Comment by Xelbayria** [comment] 2024-11-05 04:30
is this issue resolved?

**Comment by Xelbayria** [comment] 2024-11-10 10:44
Since there are no replying, will be closing this.

**Closed as not planned by Xelbayria** 2024-11-10 10:44 UTC
Labels: bug, 1.20.1-FORGE, status: noreply
