### ISSUE TITLE
[🐞]: Failed to generate recipe for...

### ISSUE THREAD

**Issue by katubug** [MehVahdJukaar/WoodGood#467] opened 2024-03-20 22:11 UTC
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.37

### Moonlight Lib Version

2.11.4

### Issue with mods

A number of them, including Regions Unexplored, Forbidden & Arcanus, Fruitful Fun, and more. I'm so sorry, I know the instructions say to do a binary search of the whole modpack, but I simply do not have that kind of energy, because the issue isn't easily replicable, and I'm not certain there's an actual conflict, as you'll see below.

### Issue Detail

Periodically when I open my game, or do /reload (I'm a pack maker so that's a lot), the game's RAM usage will spike to max and I'll get locked in a perpetual loop of 90-100% RAM usage. On rare occasions this stops on its own, but usually the client will go unresponsive and I'll have to force exit. I would say that this happens very rarely on opening a world, and about 10% of the time when I'm doing /reload.

I've included an excerpt of the latest log below (I can provide the full thing if needed). It's a bunch of `[Server thread/ERROR]: Failed to generate recipe for [whatever]`. The thing is, though, that it doesn't always have these issues. Many, if not all, of these things work just fine normally.

In the past I've had some issues with my game randomly having "resource reload" errors, which have since stopped, but occasionally my resources will just reload at inopportune times. I am not sure if it's related, but it seemed worth mentioning. I'm still looking for the cause of that.

### OPTIONAL: Latest.log | Crash-report Attachment

https://gist.github.com/katubug/2622fd118e086d52a13f6dc73458928c

**Comment by Xelbayria** [comment] 2024-03-21 09:29
The problem is **Macaw's Fences & Walls**, can you check its version and see if it's updated to the latest?

**Comment by katubug** [comment] 2024-03-21 21:40
It is version 1.1.1, which appears to be the most recent version available in the CurseForge launcher. Should I report this to them?

**Comment by Xelbayria** [comment] 2024-03-21 23:33
No. it's not their problem. it's on EC's side. I cannot replicate this bug on my side. I had no problem. I'm not sure why it failed to generate the recipes for these blocks from EC. 

EDIT: 
another thought, try to do a clean installation of EC, Moonlight, and Macaw's Fences & Walls. 
then you can check to see if the problem persists.

**Comment by katubug** [comment] 2024-03-21 23:39
It's not easy to replicate even on my side! It happens very rarely. Would it be helpful if I got the full latest.log? I'll warn you that it's enormous - I timed out submitting it to gist yesterday. I wonder if it's not just Macaw's that's being affected? I could easily see this being an issue with an unrelated third mod that just does something weirdly on /reload.

**Comment by Xelbayria** [comment] 2024-03-22 00:17
> It's not easy to replicate even on my side! It happens very rarely. Would it be helpful if I got the full latest.log? I'll warn you that it's enormous - I timed out submitting it to gist yesterday. I wonder if it's not just Macaw's that's being affected? I could easily see this being an issue with an unrelated third mod that just does something weirdly on /reload.

Try to not use `/reload` and just play the world as it is. with that, you can send me the `latest.log`. I want to check and compare the log with `/reload` and without `/reload`

EDIT: 
isn't `/reload` from **CraftTweaker**?

**Comment by Xelbayria** [comment] 2024-04-05 00:38
I haven't heard from you for a while. Have you tested without using `/reload`?

**Comment by katubug** [comment] 2024-04-05 00:46
Sorry, I've been taking a break due to burnout. I do still have this on my
radar! I'll try to get to it this week.

**Comment by katubug** [comment] 2024-04-16 23:49
Hello! So /reload in this case is from KubeJS. Unfortunately I cannot avoid using this command as I am developing the modpack myself, and I don't want to have to do a full restart each time I need to test my changes in-game.

The issue, to my knowledge, doesn't ever occur if I don't do /reload, but perhaps it's just very rare.

Here's the latest.log without /reload: https://gist.github.com/katubug/f707442466adf6349ace14f19f5ea42b

**Comment by Xelbayria** [comment] 2024-04-17 02:47
I see. **EveryComp (EC)** generates the recipe for blocks/items when you load the world. Seeing that you are developing the Modpack. You don't have to worry about the issue. As long as your Modpack is finished and good to go for public release or whatever. 
just ensure that everything is working properly, especially the recipes on **EC**'s side. You can close this issue for now, If you have an issue with the recipe from **EC** with the finished Modpack, then you can re-open this issue. 

My guess is somehow `/reload` from **KubeJS** caused the recipes from **EC** to improperly working. I'm not sure why. When your Modpack is out for official play, `/reload` must not be used.

**Closed as not planned** 2024-04-17 03:38 UTC
Labels: bug, 1.20.1-FORGE
